### ISSUE TITLE
AttributeError: module '__main__' has no attribute '__spec__'

### ISSUE THREAD

**Issue by aayushworkiitr** [pandas-profiling/pandas-profiling#122]
I am trying to run pandas_profiling function on a pandas dataframe on python version 3.6.4.
The package got imported successfully but when I am trying to use the function 
`
AD_profile=pandas_profiling.ProfileReport(final_dataset)
`
then I get  the following error.
```
Traceback (most recent call last):

  File "<ipython-input-35-e667d7ef2617>", line 1, in <module>
    AD_profile=pandas_profiling.ProfileReport(final_dataset)

  File "C:\ProgramData\Anaconda3\Lib\site-packages\pandas_profiling\__init__.py", line 66, in __init__
    description_set = describe(df, **kwargs)

  File "C:\ProgramData\Anaconda3\Lib\site-packages\pandas_profiling\describe.py", line 349, in describe
    pool = multiprocessing.Pool(pool_size)

  File "C:\ProgramData\Anaconda3\lib\multiprocessing\context.py", line 119, in Pool
    context=self.get_context())

  File "C:\ProgramData\Anaconda3\lib\multiprocessing\pool.py", line 174, in __init__
    self._repopulate_pool()

  File "C:\ProgramData\Anaconda3\lib\multiprocessing\pool.py", line 239, in _repopulate_pool
    w.start()

  File "C:\ProgramData\Anaconda3\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)

  File "C:\ProgramData\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)

  File "C:\ProgramData\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)

  File "C:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 172, in get_preparation_data
    main_mod_name = getattr(main_module.__spec__, "name", None)

AttributeError: module '__main__' has no attribute '__spec__'
```

It would be great if someone could help me fix it. 

Thanks!

**Comment by lpizarro** [comment]
I have the same issue. How did you solve it?

**Comment by aayushworkiitr** [comment]
Not sure. I tried re-installing the python package using pip and then the error went away for a couple of days. However, it has started happening again since day before yesterday!.

**Comment by xinranhou** [comment]
I have the same issue. I saw this solution, but it dosen't works for me.Would it be helpful for you? Or remind something to you somehow?
https://stackoverflow.com/questions/45720153/python-multiprocessing-error-attributeerror-module-main-has-no-attribute
