### ISSUE TITLE
ZeroDivisionError when trying to profile a dataframe with only columns of object dtype

### ISSUE THREAD

**Issue by vkk800** [pandas-profiling/pandas-profiling#143]
An example:

```
>>> df = pd.DataFrame({'a': ['a', 'b']})
>>> pandas_profiling.ProfileReport(df)
/home/me/.local/lib/python3.6/site-packages/matplotlib/axes/_base.py:2782: UserWarning: Attempting to set identical left==right results
in singular transformations; automatically expanding.
left=-0.5, right=-0.5
  'left=%s, right=%s') % (left, right))
/home/me/.local/lib/python3.6/site-packages/matplotlib/axes/_base.py:3040: UserWarning: Attempting to set identical bottom==top results
in singular transformations; automatically expanding.
bottom=-0.5, top=-0.5
  'bottom=%s, top=%s') % (bottom, top))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/me/.local/lib/python3.6/site-packages/pandas_profiling-1.4.1-py3.6.egg/pandas_profiling/__init__.py", line 69, in __init__
    moved={'CParserError': 'pandas.errors.ParserError'})
  File "/home/me/.local/lib/python3.6/site-packages/pandas_profiling-1.4.1-py3.6.egg/pandas_profiling/report.py", line 199, in to_html
  File "/home/me/.local/lib/python3.6/site-packages/pandas_profiling-1.4.1-py3.6.egg/pandas_profiling/plot.py", line 136, in correlation_matrix

ZeroDivisionError: float division by zero
```
(EDIT: removed some personal information from the error message)

The error is due to pandas-profiling trying to divide by the length of an empty dataframe in the function that plots the correlations matrices. Should be easy to fix by omitting the correlation matrix plots if there is no numerical data present in the dataframe.

**Comment by anbu004** [comment]
Hello,

Were you able to omit the correlation matrix plots, If so how were you able to omit them? Any suggestion would be greatly appreciated.

Regards,
Kishan

**Comment by dsvolk** [comment]
There is currently no way to omit them. I did so by manually hacking into the code.

**Comment by bhougland18** [comment]
I added a scalar column to the df that was a float.  It now works, but you probably want to turn the correlation off in this case.
