### ISSUE TITLE
ValueError: The 'ydata_profiling' package was not installed in a way that PackageLoader understands.

### ISSUE THREAD

**Issue by VERISBABY** [pandas-profiling/pandas-profiling#1434]
### Current Behaviour

i compile an APP use **`Pyinstaller`** and got this error when open the compiled .exe file:
```
Traceback (most recent call last):
  File "myuniverse.py", line 133, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "ydata_profiling\__init__.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "ydata_profiling\compare_reports.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "ydata_profiling\profile_report.py", line 33, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "ydata_profiling\report\presentation\flavours\html\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "ydata_profiling\report\presentation\flavours\html\alerts.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "ydata_profiling\report\presentation\flavours\html\templates.py", line 11, in <module>
  File "jinja2\loaders.py", line 323, in __init__
ValueError: The 'ydata_profiling' package was not installed in a way that PackageLoader understands.
```

### Expected Behaviour

Work after compiled use pyinstaller.

### Data Description

NONE

### Code that reproduces the bug

```Python
from ydata_profiling import ProfileReport
profile = ProfileReport(df)
```

### pandas-profiling version

v4.5.1

### Dependencies

```Text
numpy-1.25.2
pandas-2.1.0
```

### OS

windows 10

### Checklist

- [X] There is not yet another bug report for this issue in the [issue tracker](https://github.com/ydataai/pandas-profiling/issues)
- [X] The problem is reproducible from this bug report. [This guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) can help to craft a minimal bug report.
- [X] The issue has not been resolved by the entries listed under [Common Issues](https://pandas-profiling.ydata.ai/docs/master/pages/support_contrib/common_issues.html).

**Comment by fabclmnt** [comment]
Hi @VERISBABY ,

this is a know error and related with the following past issues: #175, #246 and #706. 

Please upvote the #175 issue and let us know why is this a relevant feature for you so we can understand how we can have it prioritized for development.
