### ISSUE TITLE
Pandas-profiling isn't installing

### ISSUE THREAD

**Issue by ade-mola** [pandas-profiling/pandas-profiling#184]
Hi. 
Trying to install the new version of pandas-profiling (2.0.1) throws an error:

Traceback (most recent call last):
  File "setup.py", line 1, in <module>
    import pandas_profiling
  File "/home/pandas-profiling-master/pandas_profiling/__init__.py", line 15, in <module>
    from pandas_profiling.config import config
  File "/home/pandas-profiling-master/pandas_profiling/config.py", line 5, in <module>
    import confuse
ModuleNotFoundError: No module named 'confuse'

**Comment by sbrugman** [comment]
The package requires `confuse`, however it should be installed automatically. Have you tried `pip install confuse`?

**Comment by ade-mola** [comment]
Yes. I have installed it on my local machine, plus all other dependencies, still the same error.
