### ISSUE TITLE
[Errno 13] Permission denied: '/home/user/.config/PandasProfiling'

### ISSUE THREAD

**Issue by Praneeshjai** [pandas-profiling/pandas-profiling#214]
Unable to debug what this issue could be

[Errno 13] Permission denied: '/home/user/.config/PandasProfiling'

Not sure what this is

**Comment by shub970** [comment]
Can you provide a minimum reproducible result?

**Comment by Isidoro91** [comment]
Hi guys, 
is there any update on this situation?
We get this error:
Traceback (most recent call last):

  File "<global-code>", line 3, in <module>
  File "/tmp/conda-2ba635df-06ea-417e-ab82-07affb4e2ace/real/envs/conda-env/lib/python3.6/site-packages/pandas_profiling/__init__.py", line 21, in <module>
    from pandas_profiling.config import config
  File "/tmp/conda-2ba635df-06ea-417e-ab82-07affb4e2ace/real/envs/conda-env/lib/python3.6/site-packages/pandas_profiling/config.py", line 64, in <module>
    config = Config()
  File "/tmp/conda-2ba635df-06ea-417e-ab82-07affb4e2ace/real/envs/conda-env/lib/python3.6/site-packages/pandas_profiling/config.py", line 20, in __init__
    self.config = confuse.Configuration("PandasProfiling", __name__)
  File "/tmp/conda-2ba635df-06ea-417e-ab82-07affb4e2ace/real/envs/conda-env/lib/python3.6/site-packages/confuse.py", line 912, in __init__
    self.read()
  File "/tmp/conda-2ba635df-06ea-417e-ab82-07affb4e2ace/real/envs/conda-env/lib/python3.6/site-packages/confuse.py", line 948, in read
    self._add_user_source()
  File "/tmp/conda-2ba635df-06ea-417e-ab82-07affb4e2ace/real/envs/conda-env/lib/python3.6/site-packages/confuse.py", line 926, in _add_user_source
    filename = self.user_config_path()
  File "/tmp/conda-2ba635df-06ea-417e-ab82-07affb4e2ace/real/envs/conda-env/lib/python3.6/site-packages/confuse.py", line 919, in user_config_path
    return os.path.join(self.config_dir(), CONFIG_FILENAME)
  File "/tmp/conda-2ba635df-06ea-417e-ab82-07affb4e2ace/real/envs/conda-env/lib/python3.6/site-packages/confuse.py", line 985, in config_dir
    os.makedirs(appdir)
  File "/tmp/conda-2ba635df-06ea-417e-ab82-07affb4e2ace/real/envs/conda-env/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/tmp/conda-2ba635df-06ea-417e-ab82-07affb4e2ace/real/envs/conda-env/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/.config'

We work in a distributed cluster without have access to the filesystem. At the moment we use the last version that works for us that is 1.4.2. Could you please investigate and provide us another workaround?
Thanks

**Comment by sbrugman** [comment]
@Praneeshjai @lsidoro91 Is either of you in the position to test whether https://github.com/pandas-profiling/pandas-profiling/pull/405 resolves the issue?

**Comment by mlevit** [comment]
@sbrugman I believe I have a similar issue that I just encountered when trying to run the profiling via AWS Glue Python Shell:

```
Traceback (most recent call last):
  File "/tmp/runscript.py", line 118, in <module>
    runpy.run_path(temp_file_path, run_name='__main__')
  File "/usr/local/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/local/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/glue-python-scripts-3gf4wz2w/csv_profiler.py", line 9, in <module>
  File "/glue/lib/installation/pandas_profiling/__init__.py", line 15, in <module>
    from pandas_profiling.model.messages import MessageType
  File "/glue/lib/installation/pandas_profiling/model/messages.py", line 12, in <module>
    from pandas_profiling.model.correlations import perform_check_correlation
  File "/glue/lib/installation/pandas_profiling/model/correlations.py", line 15, in <module>
    from pandas_profiling.config import config
  File "/glue/lib/installation/pandas_profiling/config.py", line 70, in <module>
    config = Config()
  File "/glue/lib/installation/pandas_profiling/config.py", line 20, in __init__
    self.config = confuse.Configuration("PandasProfiling", __name__)
  File "/glue/lib/installation/confuse.py", line 912, in __init__
    self.read()
  File "/glue/lib/installation/confuse.py", line 948, in read
    self._add_user_source()
  File "/glue/lib/installation/confuse.py", line 926, in _add_user_source
    filename = self.user_config_path()
  File "/glue/lib/installation/confuse.py", line 919, in user_config_path
    return os.path.join(self.config_dir(), CONFIG_FILENAME)
  File "/glue/lib/installation/confuse.py", line 985, in config_dir
    os.makedirs(appdir)
  File "/usr/local/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/local/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/.config'
```

I'm happy to try the fix if you can release a beta version to PyPI as Glue installs dependencies via `setup.py`.

**Comment by SudheerBondada** [comment]
@mlevit As @sbrugman  mentioned in https://github.com/beetbox/confuse/issues/70 rebuilding https://pypi.org/project/pandas-profiling/2.4.0/#files (.whl file) with `read=False` in config.py seems to work. Tested this on AWS Glue python shell (python3).

**Comment by mlevit** [comment]
Great to hear @SudheerBondada. Does that mean the change can be merged @sbrugman ?

**Comment by sbrugman** [comment]
Thanks for the feedback guys. v2.6.0 contains the fix.
