### ISSUE TITLE
Check output file name before start profiling

### ISSUE THREAD

**Issue by banderlog** [pandas-profiling/pandas-profiling#388]
**Missing functionality**
Check output file name *before* start profiling.

**Additional context**

```
[ranger]bkaba@kh1200:~/DATA$ ./venv/bin/pandas_profiling --pool_size 6 -m data/some.csv out.htm
variables: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 165/165 [02:03<00:00,  1.33it/s]
table: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:08<00:00,  8.35s/it]
warnings [correlations]: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 646.57it/s]
package: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 162.00it/s]
build report structure: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:38<00:00, 38.69s/it]
Traceback (most recent call last):
  File "./venv/bin/pandas_profiling", line 8, in <module>
    sys.exit(main())
  File "/home/bkaba/DATA/venv/lib/python3.6/site-packages/pandas_profiling/controller/console.py", line 91, in main
    p.to_file(output_file=Path(args.output_file), silent=args.silent)
  File "/home/bkaba/DATA/venv/lib/python3.6/site-packages/pandas_profiling/__init__.py", line 145, in to_file
    raise ValueError("Extension not supported (please use .html, .json)")
ValueError: Extension not supported (please use .html, .json)
```

**Comment by sbrugman** [comment]
Follow-up in #421.
