### ISSUE TITLE
KeyError: 'script_values' while generating HTML report in version 2.7.0

### ISSUE THREAD

**Issue by ankit-crossml** [pandas-profiling/pandas-profiling#468]
**Describe the bug**
I have a dataset of Camera ID's in the house with their location. I am trying to generate pandas_profiling report in HTML format and getting below error traceback:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ankit/Projects/pui/big_venv3/lib/python3.7/site-packages/pandas_profiling/profile_report.py", line 324, in to_html
    return self.html
  File "/home/ankit/Projects/pui/big_venv3/lib/python3.7/site-packages/pandas_profiling/profile_report.py", line 152, in html
    self._html = self._render_html()
  File "/home/ankit/Projects/pui/big_venv3/lib/python3.7/site-packages/pandas_profiling/profile_report.py", line 253, in _render_html
    report = self.report
  File "/home/ankit/Projects/pui/big_venv3/lib/python3.7/site-packages/pandas_profiling/profile_report.py", line 146, in report
    self._report = get_report_structure(self.description_set)
  File "/home/ankit/Projects/pui/big_venv3/lib/python3.7/site-packages/pandas_profiling/report/structure/report.py", line 250, in get_report_structure
    render_variables_section(summary),
  File "/home/ankit/Projects/pui/big_venv3/lib/python3.7/site-packages/pandas_profiling/report/structure/report.py", line 125, in render_variables_section
    template_variables.update(type_to_func[summary["type"]](template_variables))
  File "/home/ankit/Projects/pui/big_venv3/lib/python3.7/site-packages/pandas_profiling/report/structure/variables/render_categorical.py", line 147, in render_categorical
    vc = pd.Series(summary["script_values"]).value_counts()
KeyError: 'script_values'

**To Reproduce**
import numpy as np
import pandas as pd
from pandas_profiling import ProfileReport
df = pd.read_csv("duplicate_missing.csv")
profile = ProfileReport(df)
profile.to_html()

_Data:_
Please check the attached data.

[duplicate_missing.zip](https://github.com/pandas-profiling/pandas-profiling/files/4609681/duplicate_missing.zip)

**Version information:**
2.7.0

**Comment by sbrugman** [comment]
This has to do with new features in visions 0.4.2 (which are coupled to pandas-profiling v2.7.1). `pip install "visions==0.4.1"` should be a quick fix.
