### ISSUE TITLE
vc = pd.Series(summary["script_values"]).value_counts()   KeyError: 'script_values'

### ISSUE THREAD

**Issue by obouluh** [pandas-profiling/pandas-profiling#469]
**Describe the bug**

**```
Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]
Generate report structure:   0%|          | 0/1 [00:06<?, ?it/s]
Traceback (most recent call last):
  File "report.py", line 98, in <module>
    main()
  File "report.py", line 94, in main
    feature_profile_report()
  File "/home/user/.local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/.local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/user/.local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "report.py", line 72, in feature_profile_report
    data.profile_report(title=title).to_file(output_file=output_filepath)
  File "/home/user/anaconda3/lib/python3.7/site-packages/pandas_profiling/profile_report.py", line 224, in to_file
    data = self.to_html()
  File "/home/user/anaconda3/lib/python3.7/site-packages/pandas_profiling/profile_report.py", line 324, in to_html
    return self.html
  File "/home/user/anaconda3/lib/python3.7/site-packages/pandas_profiling/profile_report.py", line 152, in html
    self._html = self._render_html()
  File "/home/user/anaconda3/lib/python3.7/site-packages/pandas_profiling/profile_report.py", line 253, in _render_html
    report = self.report
  File "/home/user/anaconda3/lib/python3.7/site-packages/pandas_profiling/profile_report.py", line 146, in report
    self._report = get_report_structure(self.description_set)
  File "/home/user/anaconda3/lib/python3.7/site-packages/pandas_profiling/report/structure/report.py", line 250, in get_report_structure
    render_variables_section(summary),
  File "/home/user/anaconda3/lib/python3.7/site-packages/pandas_profiling/report/structure/report.py", line 125, in render_variables_section
    template_variables.update(type_to_func[summary["type"]](template_variables))
  File "/home/user/anaconda3/lib/python3.7/site-packages/pandas_profiling/report/structure/variables/render_categorical.py", line 147, in render_categorical
    vc = pd.Series(summary["script_values"]).value_counts()
KeyError: 'script_values'
```**

**To Reproduce**


<!--
We would need to reproduce your scenario before being able to resolve it. 

_Data:_
Please share your dataframe. 
If the data is confidential, for example when it contains company-sensitive information, provide us with a synthetic or open dataset that produces the same error. 
You should provide the DataFrame structure, for example by reporting the output of `df.info()`. 
You can anonymize the column names if necessary.

_Code:_ Preferably, use this code format:
```python
"""
Test for issue XXX:
https://github.com/pandas-profiling/pandas-profiling/issues/XXX
"""
import pandas as pd
import pandas_profiling


def test_issueXXX():
    df = pd.read_csv(r'<file>')

    # Minimal reproducible code
```
--> 

**Version information:**

**Additional context**

common environment!

**Comment by obouluh** [comment]
i cann't solve this problem .But i can replace by using minimal model .
Just like the link :
![image](https://user-images.githubusercontent.com/22076064/81650489-8e1b0f80-9464-11ea-8519-38b4ba7d9f4a.png)
