### ISSUE TITLE
OSError: [Errno 28] No space left on device

### ISSUE THREAD

**Issue by UlionTse** [pandas-profiling/pandas-profiling#518]
version==2.8.0

my data:
col 300
row 500,000
size 1.5G

my device:
```
              total        used        free      shared  buff/cache   available
Mem:            31G        419M         22G        508K        8.6G         30G
Swap:            0B          0B          0B
```

my code:
```python
def pandas_report(data):
    profile = pandas_profiling.ProfileReport(data, title='Pandas Profiling Report', explorative=True)
    profile.to_file('pandas_profiling.html')
```
Even if I set `explorative=False`, same error.

error:
```
  7 joblib.externals.loky.process_executor._RemoteTraceback:
  8 """
  9 Traceback (most recent call last):
 10   File "/installpackages/anaconda3/lib/python3.7/site-packages/joblib/externals/loky/backend/queues.py", line 150, in _feed
 11     obj_ = dumps(obj, reducers=reducers)
 12   File "/installpackages/anaconda3/lib/python3.7/site-packages/joblib/externals/loky/backend/reduction.py", line 247, in dumps
 13     dump(obj, buf, reducers=reducers, protocol=protocol)
 14   File "/installpackages/anaconda3/lib/python3.7/site-packages/joblib/externals/loky/backend/reduction.py", line 240, in dump
 15     _LokyPickler(file, reducers=reducers, protocol=protocol).dump(obj)
 16   File "/installpackages/anaconda3/lib/python3.7/site-packages/joblib/externals/cloudpickle/cloudpickle.py", line 482, in dump
 17     return Pickler.dump(self, obj)
 18   File "/installpackages/anaconda3/lib/python3.7/pickle.py", line 437, in dump
 19     self.save(obj)
 20   File "/installpackages/anaconda3/lib/python3.7/pickle.py", line 549, in save
 21     self.save_reduce(obj=obj, *rv)
 22   File "/installpackages/anaconda3/lib/python3.7/pickle.py", line 662, in save_reduce
 23     save(state)
 24   File "/installpackages/anaconda3/lib/python3.7/pickle.py", line 504, in save
 25     f(self, obj) # Call unbound method with explicit self
 26   File "/installpackages/anaconda3/lib/python3.7/pickle.py", line 859, in save_dict
 27     self._batch_setitems(obj.items())
 28   File "/installpackages/anaconda3/lib/python3.7/pickle.py", line 885, in _batch_setitems
 29     save(v)
 30   File "/installpackages/anaconda3/lib/python3.7/pickle.py", line 549, in save
 31     self.save_reduce(obj=obj, *rv)
 32   File "/installpackages/anaconda3/lib/python3.7/pickle.py", line 662, in save_reduce
 33     save(state)
 34   File "/installpackages/anaconda3/lib/python3.7/pickle.py", line 504, in save
 35     f(self, obj) # Call unbound method with explicit self
 36   File "/installpackages/anaconda3/lib/python3.7/pickle.py", line 859, in save_dict
 37     self._batch_setitems(obj.items())
 38   File "/installpackages/anaconda3/lib/python3.7/pickle.py", line 890, in _batch_setitems
 39     save(v)
 40   File "/installpackages/anaconda3/lib/python3.7/pickle.py", line 549, in save
 41     self.save_reduce(obj=obj, *rv)
 42   File "/installpackages/anaconda3/lib/python3.7/pickle.py", line 662, in save_reduce
 43     save(state)
 44   File "/installpackages/anaconda3/lib/python3.7/pickle.py", line 504, in save
 45     f(self, obj) # Call unbound method with explicit self
 46   File "/installpackages/anaconda3/lib/python3.7/pickle.py", line 859, in save_dict
 47     self._batch_setitems(obj.items())
 48   File "/installpackages/anaconda3/lib/python3.7/pickle.py", line 885, in _batch_setitems
 49     save(v)
 50   File "/installpackages/anaconda3/lib/python3.7/pickle.py", line 504, in save
 51     f(self, obj) # Call unbound method with explicit self
 52   File "/installpackages/anaconda3/lib/python3.7/pickle.py", line 819, in save_list
 53     self._batch_appends(obj)
 54   File "/installpackages/anaconda3/lib/python3.7/pickle.py", line 846, in _batch_appends
 55     save(tmp[0])
 56   File "/installpackages/anaconda3/lib/python3.7/pickle.py", line 504, in save
 57     f(self, obj) # Call unbound method with explicit self
 58   File "/installpackages/anaconda3/lib/python3.7/pickle.py", line 774, in save_tuple
 59     save(element)
 60   File "/installpackages/anaconda3/lib/python3.7/pickle.py", line 504, in save
 61     f(self, obj) # Call unbound method with explicit self
 62   File "/installpackages/anaconda3/lib/python3.7/pickle.py", line 774, in save_tuple
 63     save(element)
 64   File "/installpackages/anaconda3/lib/python3.7/pickle.py", line 549, in save
 65     self.save_reduce(obj=obj, *rv)
 66   File "/installpackages/anaconda3/lib/python3.7/pickle.py", line 662, in save_reduce
 67     save(state)
 68   File "/installpackages/anaconda3/lib/python3.7/pickle.py", line 504, in save
 69     f(self, obj) # Call unbound method with explicit self
 70   File "/installpackages/anaconda3/lib/python3.7/pickle.py", line 859, in save_dict
 71     self._batch_setitems(obj.items())
 72   File "/installpackages/anaconda3/lib/python3.7/pickle.py", line 885, in _batch_setitems
 73     save(v)
 74   File "/installpackages/anaconda3/lib/python3.7/pickle.py", line 549, in save
 75     self.save_reduce(obj=obj, *rv)
 76   File "/installpackages/anaconda3/lib/python3.7/pickle.py", line 662, in save_reduce
 77     save(state)
 78   File "/installpackages/anaconda3/lib/python3.7/pickle.py", line 504, in save
 79     f(self, obj) # Call unbound method with explicit self
 80   File "/installpackages/anaconda3/lib/python3.7/pickle.py", line 789, in save_tuple
 81     save(element)
 82   File "/installpackages/anaconda3/lib/python3.7/pickle.py", line 504, in save
 83     f(self, obj) # Call unbound method with explicit self
 84   File "/installpackages/anaconda3/lib/python3.7/pickle.py", line 819, in save_list
 85     self._batch_appends(obj)
 86   File "/installpackages/anaconda3/lib/python3.7/pickle.py", line 846, in _batch_appends
 87     save(tmp[0])
 88   File "/installpackages/anaconda3/lib/python3.7/pickle.py", line 510, in save
 89     rv = reduce(obj)
 90   File "/installpackages/anaconda3/lib/python3.7/site-packages/joblib/_memmapping_reducer.py", line 339, in __call__
 91     for dumped_filename in dump(a, filename):
 92   File "/installpackages/anaconda3/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 505, in dump
 93     NumpyPickler(f, protocol=protocol).dump(value)
 94   File "/installpackages/anaconda3/lib/python3.7/pickle.py", line 437, in dump
 95     self.save(obj)
 96   File "/installpackages/anaconda3/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 292, in save
 97     wrapper.write_array(obj, self)
 98   File "/installpackages/anaconda3/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 104, in write_array
 99     pickler.file_handle.write(chunk.tostring('C'))
100 OSError: [Errno 28] No space left on device
101 """
102
103 The above exception was the direct cause of the following exception:
104
105 Traceback (most recent call last):
106   File "model.py", line 316, in <module>
107     bm.pandas_report(bm.data)
108   File "model.py", line 33, in _wrapper
109     r = func(*args, **kwargs)
110   File "model.py", line 156, in pandas_report
111     profile.to_file('pandas_profiling.html')
112   File "/installpackages/anaconda3/lib/python3.7/site-packages/pandas_profiling/profile_report.py", line 245, in to_file
113     data = self.to_html()
114   File "/installpackages/anaconda3/lib/python3.7/site-packages/pandas_profiling/profile_report.py", line 348, in to_html
115     return self.html
116   File "/installpackages/anaconda3/lib/python3.7/site-packages/pandas_profiling/profile_report.py", line 168, in html
117     self._html = self._render_html()
118   File "/installpackages/anaconda3/lib/python3.7/site-packages/pandas_profiling/profile_report.py", line 275, in _render_html
119     report = self.report
120   File "/installpackages/anaconda3/lib/python3.7/site-packages/pandas_profiling/profile_report.py", line 162, in report
121     self._report = get_report_structure(self.description_set)
122   File "/installpackages/anaconda3/lib/python3.7/site-packages/pandas_profiling/profile_report.py", line 143, in description_set
123     self._description_set = describe_df(self.title, self.df)
124   File "/installpackages/anaconda3/lib/python3.7/site-packages/pandas_profiling/model/describe.py", line 82, in describe
125     df, variables, correlation_name
126   File "/installpackages/anaconda3/lib/python3.7/site-packages/pandas_profiling/model/correlations.py", line 168, in calculate_correlation
127     correlation = df[selcols].phik_matrix(interval_cols=intcols)
128   File "/installpackages/anaconda3/lib/python3.7/site-packages/phik/phik.py", line 217, in phik_matrix
129     drop_overflow=drop_overflow)
130   File "/installpackages/anaconda3/lib/python3.7/site-packages/phik/phik.py", line 147, in phik_from_rebinned_df
131     for co in itertools.combinations_with_replacement(data_binned.columns.values, 2))
132   File "/installpackages/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 1017, in __call__
133     self.retrieve()
134   File "/installpackages/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 909, in retrieve
135     self._output.extend(job.get(timeout=self.timeout))
136   File "/installpackages/anaconda3/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 562, in wrap_future_result
137     return future.result(timeout=timeout)
138   File "/installpackages/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 428, in result
139     return self.__get_result()
140   File "/installpackages/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
141     raise self._exception
142 _pickle.PicklingError: Could not pickle the task to send it to the workers.
```

I want to know why the calculated report result is so large that it exceeds 22G. And I cost 1.2h to finish it, whether the calculation speed can be improved, I know that the calculation correlation is n*(n-1)/2 level.
Thanks.

**Comment by sbrugman** [comment]
From the error message alone it seems that one of the correlation calculations is writing to disk. You could try to set `correlations=None` to disable all correlations and see if it solves the issue.
