### ISSUE TITLE
how do I ? Help needed on dev. environment setup - getting started

### ISSUE THREAD

**Issue by bigbprp** [pandas-profiling/pandas-profiling#540]
Hi, 

How do I set up my development environment? I am new on github projects & want to set up pandas profiling. I am using pycharm & I am unable to setup the project using pycharm. 

Any help is highly appreciated.

**Comment by sbrugman** [comment]
@bigbprp To setup the development environment please fork and clone the repository (`git clone ...`)[1] and then make the changes you're interested in. More info can be found here [2]. 

You can expect the contribution guidelines to provide information that is specific for this project, so they will not provide step-by-step commands. Luckily, Github (and other sites) provide abundant resources.

[1]: https://docs.github.com/en/github/getting-started-with-github/fork-a-repo
[2]: https://pandas-profiling.github.io/pandas-profiling/docs/master/rtd/pages/contribution_guidelines.html

**Comment by bigbprp** [comment]
Thank you very much for guidance... surprisingly, I was doing some modification by self to first understand the code. My challenge is as follows:

 **When I try to run code from pycharm community edition with latest version of pandas, it gives error. However, same main.py converted to ipynb gives no error.  so, I am wondering, if I want to add a new feature how do I debug? Since, I am new to such a large project...**

**Code: file name main.py**


from pandas_profiling .profile_report import  ProfileReport
import pandas as pd

mydf = pd.read_csv("b1.csv")
mydf.set_index("Sr", inplace = True)
mydf["Name"] = mydf["Name"].astype(str)

mydf["mydtw"] = pd.to_datetime(mydf['mydtw'], utc=False)
#print(mydf.head())

print(mydf.info())

profile = ProfileReport(mydf, title="Sun data Profiler Report" )
#profile.set_variable("html.minify_html", False)
profile.set_variable("correlations",None)
profile.set_variable("interactions",None)

profile.set_variable("samples", None)
profile.to_file("demo1.html")

**ERROR:**
Summarize dataset:  77%|███████▋  | 10/13 [00:00<00:00, 14.90it/s, Locating duplicates]
Traceback (most recent call last):
  File "D:/PycharmProjects/pandas-profiling/main.py", line 22, in <module>
    profile.to_file("demo1.html")
  File "D:\PycharmProjects\pandas-profiling\pandas-profiling\profile_report.py", line 241, in to_file
    data = self.to_html()
  File "D:\PycharmProjects\pandas-profiling\pandas-profiling\profile_report.py", line 342, in to_html
    return self.html
  File "D:\PycharmProjects\pandas-profiling\pandas-profiling\profile_report.py", line 172, in html
    self._html = self._render_html()
  File "D:\PycharmProjects\pandas-profiling\pandas-profiling\profile_report.py", line 271, in _render_html
    report = self.report
  File "D:\PycharmProjects\pandas-profiling\pandas-profiling\profile_report.py", line 166, in report
    self._report = get_report_structure(self.description_set)
  File "D:\PycharmProjects\pandas-profiling\pandas-profiling\profile_report.py", line 147, in description_set
    self._description_set = describe_df(self.title, self.df, self._sample)
  File "D:\PycharmProjects\pandas-profiling\pandas-profiling\model\describe.py", line 130, in describe
    duplicates = get_duplicates(df, supported_columns)
  File "D:\PycharmProjects\pandas-profiling\pandas-profiling\model\summary.py", line 582, in get_duplicates
    df[df.duplicated(subset=supported_columns, keep=False)]
  File "D:\pycharmprojects\pandas-profiling\venv\lib\site-packages\pandas\core\series.py", line 1292, in reset_index
    return df.reset_index(level=level, drop=drop)
  File "D:\pycharmprojects\pandas-profiling\venv\lib\site-packages\pandas\core\frame.py", line 4848, in reset_index
    level_values = _maybe_casted_values(lev, lab)
  File "D:\pycharmprojects\pandas-profiling\venv\lib\site-packages\pandas\core\frame.py", line 4781, in _maybe_casted_values
    values = construct_1d_arraylike_from_scalar(
  File "D:\pycharmprojects\pandas-profiling\venv\lib\site-packages\pandas\core\dtypes\cast.py", line 1554, in construct_1d_arraylike_from_scalar
    subarr.fill(value)
ValueError: cannot convert float NaN to integer

**CSV Data file:**

Sr,Name,Qty,mydtw
1,name1 ,513,12-08-2020
2,name3 ,237,27-07-2021
3,name2,164,20-10-2020
4,name1 1,579,01-11-2020
5,name3  1,265,08-03-2021
6,name2  1,757,10-12-2020
7,name1 1,21,05-01-2021
8,name3  1,382,15-06-2021
9,name2  1,600,18-04-2021
10,name1 1,887,12-08-2020
11,name1 ,21,12-08-2020
12,name3 ,637,18-09-2020
13,name2,74,23-08-2020
14,name1 2,286,14-05-2021
15,name3  2,100,18-11-2020
16,name2  2,251,30-06-2021
17,name1 2,868,06-01-2021
18,name3  2,543,23-06-2021

**Comment by bigbprp** [comment]
I forgot to add that I am using pandas 1.1.0 & python 3.8.0... but I doubt if that could be the reason...

**Comment by set92** [comment]
pandas 1.0.5
python 3.7.7
pandas profiling 2.8.0

And it works without any problem in jupyter notebook. I'm guessing from other issues that you are not using pandas profiling 2.8.0? Since the error is the same as #92.

**Comment by bigbprp** [comment]
Thank you.. I think, I can wait for upcoming release  & start again it seems [#92](https://github.com/pandas-profiling/pandas-profiling/issues/92).  is resolved..
