### ISSUE TITLE
Broken Process Pool Error 

### ISSUE THREAD

**Issue by gkoutsos9** [pandas-profiling/pandas-profiling#593]
When using pandas_profiling to generate a report. The process terminates at 65% (when calculating correlation) and returns a broken process pool error.

To Reproduce
I am using Jupyter Notebook 6.1.1 on an Anaconda Environment, Python 3.8 on a Windows 64 bit machine.  The data can be found here: https://github.com/lilinglu/Device-failure-prediction/blob/master/failures_prediction.csv

```
import pandas as pd
from pandas_profiling import ProfileReport
df = pd.read_csv('data.csv')
df.profile_report()
```

```
---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\k\Anaconda3\lib\site-packages\joblib\externals\loky\process_executor.py", line 404, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "C:\Users\k\Anaconda3\lib\multiprocessing\queues.py", line 116, in get
    return _ForkingPickler.loads(res)
  File "C:\Users\k\Anaconda3\lib\site-packages\phik\__init__.py", line 5, in <module>
    from phik import decorators
  File "C:\Users\k\Anaconda3\lib\site-packages\phik\decorators\__init__.py", line 4, in <module>
    from phik.decorators import pandas
  File "C:\Users\k\Anaconda3\lib\site-packages\phik\decorators\pandas.py", line 31, in <module>
    from phik.significance import significance_matrix
  File "C:\Users\k\Anaconda3\lib\site-packages\phik\significance.py", line 31, in <module>
    from .simulation import sim_chi2_distribution
  File "C:\Users\k\Anaconda3\lib\site-packages\phik\simulation.py", line 20, in <module>
    from numba import jit
  File "C:\Users\k\Anaconda3\lib\site-packages\numba\__init__.py", line 14, in <module>
    from numba.core import config
  File "C:\Users\k\Anaconda3\lib\site-packages\numba\core\config.py", line 16, in <module>
    import llvmlite.binding as ll
  File "C:\Users\k\Anaconda3\lib\site-packages\llvmlite\binding\__init__.py", line 4, in <module>
    from .dylib import *
  File "C:\Users\k\Anaconda3\lib\site-packages\llvmlite\binding\dylib.py", line 3, in <module>
    from llvmlite.binding import ffi
  File "C:\Users\k\Anaconda3\lib\site-packages\llvmlite\binding\ffi.py", line 153, in <module>
    raise OSError("Could not load shared object file: {}".format(_lib_name))
OSError: Could not load shared object file: llvmlite.dll
"""

The above exception was the direct cause of the following exception:

BrokenProcessPool                         Traceback (most recent call last)
~\Anaconda3\lib\site-packages\IPython\core\formatters.py in __call__(self, obj)
    343             method = get_real_method(obj, self.print_method)
    344             if method is not None:
--> 345                 return method()
    346             return None
    347         else:

~\Anaconda3\lib\site-packages\pandas_profiling\profile_report.py in _repr_html_(self)
    407     def _repr_html_(self):
    408         """The ipython notebook widgets user interface gets called by the jupyter notebook."""
--> 409         self.to_notebook_iframe()
    410 
    411     def __repr__(self):

~\Anaconda3\lib\site-packages\pandas_profiling\profile_report.py in to_notebook_iframe(self)
    387         with warnings.catch_warnings():
    388             warnings.simplefilter("ignore")
--> 389             display(get_notebook_iframe(self))
    390 
    391     def to_widgets(self):

~\Anaconda3\lib\site-packages\pandas_profiling\report\presentation\flavours\widget\notebook.py in get_notebook_iframe(profile)
     63         output = get_notebook_iframe_src(profile)
     64     elif attribute == "srcdoc":
---> 65         output = get_notebook_iframe_srcdoc(profile)
     66     else:
     67         raise ValueError(

~\Anaconda3\lib\site-packages\pandas_profiling\report\presentation\flavours\widget\notebook.py in get_notebook_iframe_srcdoc(profile)
     21     width = config["notebook"]["iframe"]["width"].get(str)
     22     height = config["notebook"]["iframe"]["height"].get(str)
---> 23     src = html.escape(profile.to_html())
     24 
     25     iframe = f'<iframe width="{width}" height="{height}" srcdoc="{src}" frameborder="0" allowfullscreen></iframe>'

~\Anaconda3\lib\site-packages\pandas_profiling\profile_report.py in to_html(self)
    357 
    358         """
--> 359         return self.html
    360 
    361     def to_json(self) -> str:

~\Anaconda3\lib\site-packages\pandas_profiling\profile_report.py in html(self)
    177     def html(self):
    178         if self._html is None:
--> 179             self._html = self._render_html()
    180         return self._html
    181 

~\Anaconda3\lib\site-packages\pandas_profiling\profile_report.py in _render_html(self)
    284         from pandas_profiling.report.presentation.flavours import HTMLReport
    285 
--> 286         report = self.report
    287 
    288         disable_progress_bar = not config["progress_bar"].get(bool)

~\Anaconda3\lib\site-packages\pandas_profiling\profile_report.py in report(self)
    171     def report(self):
    172         if self._report is None:
--> 173             self._report = get_report_structure(self.description_set)
    174         return self._report
    175 

~\Anaconda3\lib\site-packages\pandas_profiling\profile_report.py in description_set(self)
    152     def description_set(self):
    153         if self._description_set is None:
--> 154             self._description_set = describe_df(self.title, self.df, self._sample)
    155         return self._description_set
    156 

~\Anaconda3\lib\site-packages\pandas_profiling\model\describe.py in describe(title, df, sample)
     88         for correlation_name in correlation_names:
     89             pbar.set_postfix_str(f"Calculate {correlation_name} correlation")
---> 90             correlations[correlation_name] = calculate_correlation(
     91                 df, variables, correlation_name
     92             )

~\Anaconda3\lib\site-packages\pandas_profiling\model\correlations.py in calculate_correlation(df, variables, correlation_name)
    166             if len(selcols) > 1:
    167                 try:
--> 168                     correlation = df[selcols].phik_matrix(interval_cols=intcols)
    169 
    170                     # Only do this if the column_order is set

~\Anaconda3\lib\site-packages\phik\phik.py in phik_matrix(df, interval_cols, bins, quantile, noise_correction, dropna, drop_underflow, drop_overflow)
    214     data_binned, binning_dict = bin_data(df_clean, cols=interval_cols_clean, bins=bins, quantile=quantile, retbins=True)
    215 
--> 216     return phik_from_rebinned_df(
    217         data_binned, noise_correction, dropna=dropna, drop_underflow=drop_underflow, drop_overflow=drop_overflow
    218     )

~\Anaconda3\lib\site-packages\phik\phik.py in phik_from_rebinned_df(data_binned, noise_correction, dropna, drop_underflow, drop_overflow)
    141         ]
    142     else:
--> 143         phik_list = Parallel(n_jobs=NCORES)(
    144             delayed(_calc_phik)(co, data_binned[list(co)], noise_correction)
    145             for co in itertools.combinations_with_replacement(data_binned.columns.values, 2)

~\Anaconda3\lib\site-packages\joblib\parallel.py in __call__(self, iterable)
   1040 
   1041             with self._backend.retrieval_context():
-> 1042                 self.retrieve()
   1043             # Make sure that we get a last message telling us we are done
   1044             elapsed_time = time.time() - self._start_time

~\Anaconda3\lib\site-packages\joblib\parallel.py in retrieve(self)
    919             try:
    920                 if getattr(self._backend, 'supports_timeout', False):
--> 921                     self._output.extend(job.get(timeout=self.timeout))
    922                 else:
    923                     self._output.extend(job.get())

~\Anaconda3\lib\site-packages\joblib\_parallel_backends.py in wrap_future_result(future, timeout)
    540         AsyncResults.get from multiprocessing."""
    541         try:
--> 542             return future.result(timeout=timeout)
    543         except CfTimeoutError as e:
    544             raise TimeoutError from e

~\Anaconda3\lib\concurrent\futures\_base.py in result(self, timeout)
    437                 raise CancelledError()
    438             elif self._state == FINISHED:
--> 439                 return self.__get_result()
    440             else:
    441                 raise TimeoutError()

~\Anaconda3\lib\concurrent\futures\_base.py in __get_result(self)
    386     def __get_result(self):
    387         if self._exception:
--> 388             raise self._exception
    389         else:
    390             return self._result

BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.
```

**Comment by gkoutsos9** [comment]
Just needed to install llvmlite.dll

**Comment by akrulz** [comment]
following fixes this
conda install --channel numba llvmlite
