### ISSUE TITLE
Profile  Report does not show anymore with Streamlit

### ISSUE THREAD

**Issue by fabioannovazzi** [pandas-profiling/pandas-profiling#654]
Hi,

If I run the profiler in streamlit (example streamlit run https://raw.githubusercontent.com/okld/streamlit-pandas-profiling/master/examples/streamlit_pandas_profiling_demo.py) I get a message "generating profile report" but no actual report. 

I get this error in Powershell 

```
2020-12-30 19:24:41.444 Uncaught exception GET /component/streamlit_pandas_profiling.pandas_profiling/fonts/IBM_Plex_Sans/IBMPlexSans-Regular.ttf (::1)
HTTPServerRequest(protocol='http', host='localhost:8501', method='GET', uri='/component/streamlit_pandas_profiling.pandas_profiling/fonts/IBM_Plex_Sans/IBMPlexSans-Regular.ttf', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "c:\users\toshiba\anaconda3\lib\site-packages\tornado\web.py", line 1701, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "c:\users\toshiba\anaconda3\lib\site-packages\streamlit\components\v1\components.py", line 324, in get
    contents = file.read()
  File "c:\users\toshiba\anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 210: character maps to <undefined>
2020-12-30 19:24:41.446 500 GET /component/streamlit_pandas_profiling.pandas_profiling/fonts/IBM_Plex_Sans/IBMPlexSans-Regular.ttf (::1) 3.00ms
```

To reproduce, simply run the report with the test link

Thanks

Fabio

**Comment by sbrugman** [comment]
Hi Fabio, thanks for reporting

I guess this issue is better raised at https://github.com/okld/streamlit-pandas-profiling/issues, since it's relevant to that code
