### ISSUE TITLE
Crashes jupyter notebook on Mac M1

### ISSUE THREAD

**Issue by johnnyheineken** [pandas-profiling/pandas-profiling#687]
**Describe the bug**

When importing:
`from pandas_profiling import ProfileReport`

jupyter kernel crashes on Apple Silicon:

> The kernel appears to have died. It will restart automatically.

**To Reproduce**
see description
_Data:_
see description
_Code:_ Preferably, use this code format:
see description

**Version information:**

Version information is essential in reproducing and resolving bugs. Please report:

* _Python version_: sys.version_info(major=3, minor=9, micro=1, releaselevel='final', serial=0) Miniforge distribution: https://github.com/conda-forge/miniforge
* _Environment_: Jupyter Notebook kernel

<details><summary>Click to expand  <strong><em>conda list</em></strong></summary>
<p>

```
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
appnope                   0.1.2            py39h2804cbe_1    conda-forge
argon2-cffi               20.1.0           py39h46acfd9_2    conda-forge
astroid                   2.4.2                    pypi_0    pypi
async_generator           1.10                       py_0    conda-forge
attrs                     20.3.0             pyhd3deb0d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
black                     20.8b1                     py_1    conda-forge
bleach                    3.3.0              pyh44b312d_0    conda-forge
brotlipy                  0.7.0           py39h51e6412_1001    conda-forge
bzip2                     1.0.8                h27ca646_4    conda-forge
ca-certificates           2020.12.5            h4653dfc_0    conda-forge
certifi                   2020.12.5        py39h2804cbe_1    conda-forge
cffi                      1.14.4           py39h702c04f_1    conda-forge
chardet                   4.0.0            py39h2804cbe_0    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
conda                     4.9.2            py39h2804cbe_0    conda-forge
conda-package-handling    1.7.2            py39h51e6412_0    conda-forge
cryptography              3.3.1            py39h0bed37e_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
dataclasses               0.7                pyhb2cacf7_7    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
freetype                  2.10.4               h17b34a0_1    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
importlib-metadata        3.4.0            py39h2804cbe_0    conda-forge
importlib_metadata        3.4.0                hd8ed1ab_0    conda-forge
ipykernel                 5.1.0              pyh24bf2e0_0    conda-forge
ipython                   7.20.0           py39h32adebf_2    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.6.3              pyhd3deb0d_0    conda-forge
isort                     5.7.0                    pypi_0    pypi
jedi                      0.18.0           py39h2804cbe_2    conda-forge
jinja2                    2.11.3             pyh44b312d_0    conda-forge
joblib                    1.0.0              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   h27ca646_0    conda-forge
jsonschema                3.2.0                      py_2    conda-forge
jupyter                   1.0.0            py39h2804cbe_6    conda-forge
jupyter_client            6.1.11             pyhd8ed1ab_1    conda-forge
jupyter_console           6.2.0                      py_0    conda-forge
jupyter_core              4.7.1            py39h2804cbe_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_widgets        1.0.0              pyhd8ed1ab_1    conda-forge
kiwisolver                1.3.1            py39h5a63225_1    conda-forge
lazy-object-proxy         1.4.3                    pypi_0    pypi
lcms2                     2.11                 h2f7874f_1    conda-forge
libblas                   3.9.0                8_openblas    conda-forge
libcblas                  3.9.0                8_openblas    conda-forge
libcxx                    11.0.1               h168391b_0    conda-forge
libffi                    3.3                  h9f76cd9_2    conda-forge
libgfortran               5.0.0.dev0      11_0_0_hdc626ea_17    conda-forge
libgfortran5              11.0.0.dev0         hdc626ea_17    conda-forge
liblapack                 3.9.0                8_openblas    conda-forge
libopenblas               0.3.12          openmp_h2ecc587_1    conda-forge
libpng                    1.6.37               hf7e6567_2    conda-forge
libsodium                 1.0.18               h27ca646_1    conda-forge
libtiff                   4.2.0                h70663a0_0    conda-forge
libwebp-base              1.2.0                h27ca646_0    conda-forge
lightgbm                  3.1.1            py39h93dc1e2_0    conda-forge
llvm-openmp               11.0.1               hb3022d6_0    conda-forge
lz4-c                     1.9.3                h9f76cd9_0    conda-forge
markupsafe                1.1.1            py39h46acfd9_3    conda-forge
matplotlib                3.3.4            py39hdf13c20_0    conda-forge
matplotlib-base           3.3.4            py39h3e8bbd8_0    conda-forge
mccabe                    0.6.1                    pypi_0    pypi
mistune                   0.8.4           py39h46acfd9_1003    conda-forge
mypy_extensions           0.4.3            py39h2804cbe_3    conda-forge
nbclient                  0.5.1                      py_0    conda-forge
nbconvert                 6.0.7            py39h2804cbe_3    conda-forge
nbformat                  5.1.2              pyhd8ed1ab_1    conda-forge
ncurses                   6.2                  h9aa5885_4    conda-forge
nest-asyncio              1.4.3              pyhd8ed1ab_0    conda-forge
notebook                  6.2.0            py39h2804cbe_0    conda-forge
numpy                     1.20.0           py39h69a04d8_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openssl                   1.1.1i               h27ca646_0    conda-forge
packaging                 20.9               pyh44b312d_0    conda-forge
pandas                    1.2.1            py39ha4bedbf_0    conda-forge
pandas-profiling          1.4.2                      py_0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.8.1              pyhd8ed1ab_0    conda-forge
pathspec                  0.8.1              pyhd3deb0d_0    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.1.0            py39hfbe1b89_1    conda-forge
pip                       20.3.3             pyhd8ed1ab_0    conda-forge
plotly                    4.14.3             pyh44b312d_0    conda-forge
plotly_express            0.4.1                      py_0    conda-forge
prometheus_client         0.9.0              pyhd3deb0d_0    conda-forge
prompt-toolkit            3.0.14             pyha770c72_0    conda-forge
prompt_toolkit            3.0.14               hd8ed1ab_0    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pycosat                   0.6.3           py39h51e6412_1005    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygments                  2.7.4              pyhd8ed1ab_0    conda-forge
pylint                    2.6.0                    pypi_0    pypi
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyrsistent                0.17.3           py39h46acfd9_2    conda-forge
pysocks                   1.7.1            py39h0caf4da_2    conda-forge
python                    3.9.1           hcbd9b3a_2_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.9                      1_cp39    conda-forge
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
pyzmq                     22.0.1           py39hc82af31_0    conda-forge
readline                  8.0                  hc8eb9b7_2    conda-forge
regex                     2020.11.13       py39h46acfd9_1    conda-forge
requests                  2.25.1             pyhd3deb0d_0    conda-forge
retrying                  1.3.3                      py_2    conda-forge
ruamel_yaml               0.15.80         py39h51e6412_1003    conda-forge
scikit-learn              0.24.1           py39hb966dd2_0    conda-forge
scipy                     1.6.0            py39h73ea49b_0    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                49.6.0           py39h0caf4da_2    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.34.0               h6d56c25_0    conda-forge
statsmodels               0.12.2           py39h038c1d3_0    conda-forge
terminado                 0.9.2            py39h2804cbe_0    conda-forge
testpath                  0.4.4                      py_0    conda-forge
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
tk                        8.6.10               hf7e6567_1    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tornado                   6.1              py39h46acfd9_1    conda-forge
tqdm                      4.55.0             pyhd8ed1ab_0    conda-forge
traitlets                 5.0.5                      py_0    conda-forge
typed-ast                 1.4.2            py39h46acfd9_0    conda-forge
typing_extensions         3.7.4.3                    py_0    conda-forge
tzdata                    2020f                he74cb21_0    conda-forge
urllib3                   1.26.2             pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
widgetsnbextension        3.5.1            py39h2804cbe_4    conda-forge
wrapt                     1.12.1                   pypi_0    pypi
xz                        5.2.5                h642e427_1    conda-forge
yaml                      0.2.5                h642e427_0    conda-forge
zeromq                    4.3.4                h9f76cd9_0    conda-forge
zipp                      3.4.0                      py_0    conda-forge
zlib                      1.2.11            h31e879b_1009    conda-forge
zstd                      1.4.8                h5b28eab_1    conda-forge
```

</p>
</details>

**Comment by johnnyheineken** [comment]
when running as .py file, `profile = ProfileReport(data, title="Pandas Profiling Report")` hangs.  

When interrupted, following error is shown:

<details><summary>Error, click to expand</summary>

```
Traceback (most recent call last):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/janhynek/miniforge3/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
  File "/Users/janhynek/miniforge3/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
  File "/Users/janhynek/miniforge3/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "<frozen importlib._bootstrap_external>", line 93, in _path_is_mode_type
  File "/Users/janhynek/miniforge3/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<frozen importlib._bootstrap_external>", line 87, in _path_stat
  File "/Users/janhynek/miniforge3/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
  File "/Users/janhynek/miniforge3/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
Traceback (most recent call last):
  File "/Users/janhynek/Documents/Python/supply_chain/eda.py", line 24, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/Users/janhynek/miniforge3/lib/python3.9/site-packages/pandas/core/groupby/__init__.so'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/janhynek/miniforge3/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    profile = ProfileReport(data, title="Pandas Profiling Report")
  File "/Users/janhynek/miniforge3/lib/python3.9/site-packages/pandas_profiling/__init__.py", line 66, in __init__
    description_set = describe_df(df, **kwargs)
  File "/Users/janhynek/miniforge3/lib/python3.9/site-packages/pandas_profiling/describe.py", line 363, in describe
    ldesc = {col: s for col, s in pool.map(local_multiprocess_func, df.iteritems())}
  File "/Users/janhynek/miniforge3/lib/python3.9/multiprocessing/pool.py", line 364, in map
    exitcode = _main(fd, parent_sentinel)
  File "/Users/janhynek/miniforge3/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/janhynek/miniforge3/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    exitcode = _main(fd, parent_sentinel)
    exitcode = _main(fd, parent_sentinel)
  File "/Users/janhynek/miniforge3/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
  File "/Users/janhynek/miniforge3/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/janhynek/miniforge3/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    prepare(preparation_data)
  File "/Users/janhynek/miniforge3/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    prepare(preparation_data)
  File "/Users/janhynek/miniforge3/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/janhynek/miniforge3/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    _fixup_main_from_path(data['init_main_from_path'])
    prepare(preparation_data)
  File "/Users/janhynek/miniforge3/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
  File "/Users/janhynek/miniforge3/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    return self._map_async(func, iterable, mapstar, chunksize).get()
    exitcode = _main(fd, parent_sentinel)
  File "/Users/janhynek/miniforge3/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
  File "/Users/janhynek/miniforge3/lib/python3.9/multiprocessing/pool.py", line 765, in get
    exitcode = _main(fd, parent_sentinel)
  File "/Users/janhynek/miniforge3/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/janhynek/miniforge3/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    exitcode = _main(fd, parent_sentinel)
    _fixup_main_from_path(data['init_main_from_path'])
    prepare(preparation_data)
  File "/Users/janhynek/miniforge3/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
  File "/Users/janhynek/miniforge3/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
  File "/Users/janhynek/miniforge3/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/janhynek/miniforge3/lib/python3.9/runpy.py", line 268, in run_path
    _fixup_main_from_path(data['init_main_from_path'])
    prepare(preparation_data)
  File "/Users/janhynek/miniforge3/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
  File "/Users/janhynek/miniforge3/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    main_content = runpy.run_path(main_path,
  File "/Users/janhynek/miniforge3/lib/python3.9/runpy.py", line 268, in run_path
    main_content = runpy.run_path(main_path,
  File "/Users/janhynek/miniforge3/lib/python3.9/runpy.py", line 268, in run_path
    main_content = runpy.run_path(main_path,
  File "/Users/janhynek/miniforge3/lib/python3.9/runpy.py", line 268, in run_path
    main_content = runpy.run_path(main_path,
  File "/Users/janhynek/miniforge3/lib/python3.9/runpy.py", line 268, in run_path
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/janhynek/miniforge3/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    prepare(preparation_data)
  File "/Users/janhynek/miniforge3/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    return _run_module_code(code, init_globals, run_name,
  File "/Users/janhynek/miniforge3/lib/python3.9/runpy.py", line 97, in _run_module_code
    return _run_module_code(code, init_globals, run_name,
    return _run_module_code(code, init_globals, run_name,
  File "/Users/janhynek/miniforge3/lib/python3.9/runpy.py", line 97, in _  File "/Users/janhynek/miniforge3/lib/python3.9/runpy.py", line 97, in _run_module_code
run_module_code
    _fixup_main_from_path(data['init_main_from_path'])
    _run_code(code, mod_globals, init_globals,
    main_content = runpy.run_path(main_path,
  File "/Users/janhynek/miniforge3/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
  File "/Users/janhynek/miniforge3/lib/python3.9/runpy.py", line 268, in run_path
  File "/Users/janhynek/miniforge3/lib/python3.9/runpy.py", line 87, in _run_code
    return _run_module_code(code, init_globals, run_name,
  File "/Users/janhynek/miniforge3/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/janhynek/miniforge3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/janhynek/Documents/Python/supply_chain/eda.py", line 2, in <module>
    exec(code, run_globals)
  File "/Users/janhynek/Documents/Python/supply_chain/eda.py", line 3, in <module>
    self.wait(timeout)
    return _run_module_code(code, init_globals, run_name,
  File "/Users/janhynek/miniforge3/lib/python3.9/runpy.py", line 97, in _run_module_code
  File "/Users/janhynek/miniforge3/lib/python3.9/multiprocessing/pool.py", line 762, in wait
    main_content = runpy.run_path(main_path,
  File "/Users/janhynek/miniforge3/lib/python3.9/runpy.py", line 268, in run_path
    _run_code(code, mod_globals, init_globals,
    return _run_module_code(code, init_globals, run_name,
  File "/Users/janhynek/miniforge3/lib/python3.9/runpy.py", line 87, in _run_code
  File "/Users/janhynek/miniforge3/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/janhynek/miniforge3/lib/python3.9/runpy.py", line 87, in _run_code
    import pandas as pd
  File "/Users/janhynek/miniforge3/lib/python3.9/site-packages/pandas/__init__.py", line 51, in <module>
    from pandas_profiling import ProfileReport
    exec(code, run_gl    _run_code(code, mod_globals, init_globals,
    _run_code(code, mod_globals, init_globals,
obals)
  File "/Users/janhynek/miniforge3/lib/python3.9/site-packages/pandas_profiling/__init__.py", line 10, in <module>
  File "/Users/janhynek/miniforge3/lib/python3.9/runpy.py", line 87, in _run_code
    return _run_module_code(code, init_globals, run_name,
  File "/Users/janhynek/miniforge3/lib/python3.9/runpy.py", line 87, in _run_code
  File "/Users/janhynek/miniforge3/lib/python3.9/runpy.py", line 97, in _run_module_code
    self._event.wait(timeout)
  File "/Users/janhynek/miniforge3/lib/python3.9/threading.py", line 574, in wait
    exec(code, run_globals)
  File "/Users/janhynek/Documents/Python/supply_chain/eda.py", line 3, in <module>
    from pandas_profiling import ProfileReport
  File "/Users/janhynek/miniforge3/lib/python3.9/site-packages/pandas_profiling/__init__.py", line 11, in <module>
    exec(code, run_globals)
  File "/Users/janhynek/Documents/Python/supply_chain/eda.py", line 3, in <module>
    exec(code, run_globals)
  File "/Users/janhynek/Documents/Python/supply_chain/eda.py", line 2, in <module>
    from pandas.core.api import (
    from pandas_profiling.describe import describe as describe_df
    import pandas_profiling.templates as templates
    _run_code(code, mod_globals, init_globals,
  File "/Users/janhynek/miniforge3/lib/python3.9/site-packages/pandas_profiling/templates.py", line 7, in <module>
  File "/Users/janhynek/miniforge3/lib/python3.9/site-packages/pandas_profiling/describe.py", line 8, in <module>
  File "/Users/janhynek/miniforge3/lib/python3.9/runpy.py", line 87, in _run_code
    from pandas_profiling import ProfileReport
  File "/Users/janhynek/miniforge3/lib/python3.9/site-packages/pandas_profiling/__init__.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
    import pandas_profiling.templates as templates
  File "/Users/janhynek/miniforge3/lib/python3.9/site-packages/pandas_profiling/templates.py", line 7, in <module>
  File "/Users/janhynek/Documents/Python/supply_chain/eda.py", line 3, in <module>
    signaled = self._cond.wait(timeout)
    import pandas as pd
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
    import matplotlib
    pl = PackageLoader('pandas_profiling', 'templates')
  File "/Users/janhynek/miniforge3/lib/python3.9/site-packages/matplotlib/__init__.py", line 94, in <module>
  File "/Users/janhynek/miniforge3/lib/python3.9/site-packages/pandas/__init__.py", line 51, in <module>
  File "/Users/janhynek/miniforge3/lib/python3.9/threading.py", line 312, in wait
  File "/Users/janhynek/miniforge3/lib/python3.9/site-packages/jinja2/loaders.py", line 233, in __init__
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
    exec(code, run_globals)
  File "<frozen importlib._bootstrap_external>", line 786, in exec_module
  File "/Users/janhynek/Documents/Python/supply_chain/eda.py", line 2, in <module>
  File "<frozen importlib._boots    waiter.acquire()
trap_external>", line 881, in get_code
    from pandas_profiling import ProfileReport
    import pandas as pd
    from pandas.core.api import (
  File "/Users/janhynek/miniforge3/lib/python3.9/site-packages/pandas/__init__.py", line 11, in <module>
  File "/Users/janhynek/miniforge3/lib/python3.9/site-packages/pandas_profiling/__init__.py", line 11, in <module>
KeyboardInterrupt
  File "/Users/janhynek/miniforge3/lib/python3.9/site-packages/pandas/core/api.py", line 31, in <module>
  File "<frozen importlib._bootstrap_external>", line 979, in get_data
    pl = PackageLoader('pandas_profiling', 'templates')
  File "/Users/janhynek/miniforge3/lib/python3.9/site-packages/jinja2/loaders.py", line 233, in __init__
    __import__(dependency)
KeyboardInterrupt
  File "/Users/janhynek/miniforge3/lib/python3.9/site-packages/numpy/__init__.py", line 145, in <module>
    from pandas.core.groupby import Grouper, NamedAgg
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_    from pandas_profiling.describe import describe as describe_df
load
  File "/Users/janhynek/miniforge3/lib/python3.9/site-packages/pandas_profiling/describe.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
    import matplotlib
  File "/Users/janhynek/miniforge3/lib/python3.9/site-packages/matplotlib/__init__.py", line 107, in <module>
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1349, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1321, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1465, in find_spec
  File "<frozen importlib._bootstrap_external>", line 101, in _path_isfile
    from pkg_resources import DefaultProvider
  File "/Users/janhynek/miniforge3/lib/python3.9/site-packages/pkg_resources/__init__.py", line 83, in <module>
    from pkg_resources import DefaultProvider
  File "<frozen importlib._bootstrap>", line 1007, in     from . import cbook, rcsetup
  File "<frozen importlib._bootstrap_external>", line 93, in _path_is_mode_type
  File "/Users/janhynek/miniforge3/lib/python3.9/site-packages/matplotlib/rcsetup.py", line 28, in <module>
_find_and_load
KeyboardInterrupt
    __import__('pkg_resources.extern.packaging.requirements')
  File "/Users/janhynek/miniforge3/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 51, in <module>
    import logging
  File "/Users/janhynek/miniforge3/lib/python3.9/logging/__init__.py", line 435, in <module>
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
    from matplotlib.fontconfig_pattern import parse_fontconfig_pattern
  File "/Users/janhynek/miniforge3/lib/python3.9/site-packages/matplotlib/fontconfig_pattern.py", line 174, in <module>
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 786, in exec_module
    from . import core
  File "/Users/janhynek/miniforge3/lib/python3.9/site-packages/numpy/core/__init__.py", line 102, in <module>
  File "<frozen importlib._bootstrap_external>", line 881, in get_code
  File "<frozen importlib._bootstrap_external>", line 979, in get_data
KeyboardInterrupt
    VERSION_PEP440 = Regex(Specifier._regex_str, re.VERBOSE | re.IGNORECASE)
  File "/Users/janhynek/miniforge3/lib/python3.9/site-packages/pkg_resources/_vendor/pyparsing.py", line 2792, in __init__
    parse_fontconfig_pattern = lru_cache()(FontconfigPatternParser().parse)
    
   ```

**Comment by sbrugman** [comment]
@johnnyheineken You are on `pandas-profiling 1.4.2`. This is a known issue with conda (sometimes caused by mixed conda and pip installs). You can resolve this issue by explictly installing 2.9.0.

**Comment by johnnyheineken** [comment]
thanks a lot. how can I install it though?

This is the report I get:

```
(base) janhynek@Jan-MacBook-Air supply_chain % conda install pandas-profiling==2.9.0
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                      

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

(base) janhynek@Jan-MacBook-Air supply_chain % 
```
