### ISSUE TITLE
descriptions per variable raises ValueError

### ISSUE THREAD

**Issue by hkennyv** [pandas-profiling/pandas-profiling#698]
**Describe the bug**

The "descriptions per variable" feature described [in the metadata section of the docs](https://pandas-profiling.github.io/pandas-profiling/docs/master/rtd/pages/metadata.html) does not seem to work yet. So far, I've tried both the inline dictionary syntax as well as using an external JSON file (see the snippets below).

**To Reproduce**

 

Here's a simple snippet:

**main.py**

```python
import pandas as pd

from pandas_profiling import ProfileReport

df = pd.DataFrame(data={"A": [1, 2, 3, 4, 5], "B": [2, 4, 6, 8, 10]})

profile = ProfileReport(df, variables={"A": "The A column", "B": "The B Column"})
```

When running `python main.py`:

```
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    profile = ProfileReport(df, variables={"A": "The A column", "B": "The B Column"})
  File "/home/hkennyv/Documents/stackoverflow/py/venv/lib/python3.7/site-packages/pandas_profiling/profile_report.py", line 80, in __init__
    config.set_kwargs(kwargs)
  File "/home/hkennyv/Documents/stackoverflow/py/venv/lib/python3.7/site-packages/pandas_profiling/config.py", line 148, in set_kwargs
    self._set_kwargs(self.config, kwargs)
  File "/home/hkennyv/Documents/stackoverflow/py/venv/lib/python3.7/site-packages/pandas_profiling/config.py", line 93, in _set_kwargs
    self._set_kwargs(reference[key], value)
  File "/home/hkennyv/Documents/stackoverflow/py/venv/lib/python3.7/site-packages/pandas_profiling/config.py", line 97, in _set_kwargs
    raise ValueError(f'Config parameter "{key}" does not exist.')
ValueError: Config parameter "A" does not exist.
```

**Version information:**

<details><summary>Click to expand <strong><em>Version information</em></strong></summary>
<p>

```
Python version: 3.7.1
Environment: command line (inside a virtualenv)
Pip freeze:

aniso8601==8.0.0
appdirs==1.4.4
argon2-cffi==20.1.0
async-generator==1.10
attrs==19.3.0
backcall==0.1.0
black==20.8b1
bleach==3.3.0
certifi==2019.11.28
cffi==1.14.5
chardet==3.0.4
click==7.1.2
confuse==1.4.0
cycler==0.10.0
decorator==4.4.1
defusedxml==0.6.0
empyrical==0.5.3
entrypoints==0.3
Flask==1.1.2
flask-restplus==0.13.0
htmlmin==0.1.12
idna==2.8
ImageHash==4.2.0
impedance==0.2.0
importlib-metadata==1.5.0
ipykernel==5.4.3
ipython==7.12.0
ipython-genutils==0.2.0
ipywidgets==7.6.3
itsdangerous==1.1.0
jedi==0.16.0
Jinja2==2.11.2
joblib==0.14.1
jsonschema==3.2.0
jupyter-client==6.1.11
jupyter-core==4.7.1
jupyterlab-pygments==0.1.2
jupyterlab-widgets==1.0.0
kiwisolver==1.1.0
llvmlite==0.35.0
lxml==4.5.0
MarkupSafe==1.1.1
matplotlib==3.3.4
missingno==0.4.2
mistune==0.8.4
more-itertools==8.2.0
mypy-extensions==0.4.3
nbclient==0.5.2
nbconvert==6.0.7
nbformat==5.1.2
nest-asyncio==1.5.1
networkx==2.5
notebook==6.2.0
numba==0.52.0
numpy==1.18.1
packaging==20.3
pandas==1.2.2
pandas-datareader==0.8.1
pandas-profiling==2.10.1
pandocfilters==1.4.3
parso==0.6.1
pathspec==0.8.1
pexpect==4.8.0
phik==0.11.0
pickleshare==0.7.5
Pillow==8.1.0
pluggy==0.13.1
prometheus-client==0.9.0
prompt-toolkit==3.0.3
ptyprocess==0.6.0
py==1.8.1
pycparser==2.20
pyfolio==0.9.2
Pygments==2.5.2
pyparsing==2.4.6
pyrsistent==0.16.0
pyspellchecker==0.5.4
pytest==5.3.5
python-dateutil==2.8.1
pytz==2019.3
PyWavelets==1.1.1
PyYAML==5.4.1
pyzmq==22.0.3
regex==2020.11.13
requests==2.25.1
scikit-learn==0.21.3
scipy==1.4.1
seaborn==0.11.1
Send2Trash==1.5.0
six==1.14.0
tangled-up-in-unicode==0.0.6
terminado==0.9.2
testpath==0.4.4
toml==0.10.2
tornado==6.1
tqdm==4.56.2
traitlets==4.3.3
typed-ast==1.4.2
typing-extensions==3.7.4.3
urllib3==1.25.8
visions==0.6.0
wcwidth==0.1.8
webencodings==0.5.1
Werkzeug==1.0.1
widgetsnbextension==3.5.1
zipp==3.1.0

```

</p>
</details>

**Additional context**

It _seems_ like we would just need to add `variables` to the constructor for `ProfileReport` so it doesn't get thrown into the `configs.set_kwargs(kwargs)` statement.

https://github.com/hkennyv/pandas-profiling/blob/a8e836220c812b8dbea09552ad000d1c3875378a/src/pandas_profiling/profile_report.py#L30-L42

I would be happy to contribute if someone could point me in the right direction :)

**EDIT:** I was able to workaround it and set the descriptions using the `.set_variable` method:

```python
import pandas as pd

from pandas_profiling import ProfileReport

df = pd.DataFrame(data={"A": [1, 2, 3, 4, 5], "B": [2, 4, 6, 8, 10]})

profile = ProfileReport(df)

profile.set_variable(
    "variable.descriptions", {"A": "The A column", "B": "The B column"}
)
```

This works, but I still think it would be nice to be able to set this option through the constructor (IMO).

**Comment by sbrugman** [comment]
This is actually a bug, both interfaces should be consistent. These are the only dynamic configuration keys, where all others are known in advance, which is causing the issue.

Note that the analogous call to `set_variable` is `profile = ProfileReport(df, variables={"descriptions": {"A": "The A column", "B": "The B Column"}})`, however this results in the same error.
