### ISSUE TITLE
pandas-profiling crashes if there are some unwanted characters in text fields

### ISSUE THREAD

**Issue by vgroshev** [pandas-profiling/pandas-profiling#707]
I am trying to apply profiler for data extracted from SAP. Data size is 1 million rows and 42 columns.
I load it to dataframe dfp and use the following code:

```
pand_prof_name = os.path.join(rep_folder, "pandas_profiler.html")
pandas_profiling.ProfileReport(dfp).to_file(pand_prof_name)
```

After analysis starts, something goes wrong and the following error occurs:

```
HBox(children=(HTML(value='variables'), FloatProgress(value=0.0, max=1.0), HTML(value='')))

Произошла ошибка.Traceback (most recent call last):
  File "C:\Users\groshev3-vn\Documents\20210215 backend_test\pmprofiler\profiler.py", line 365, in create_report
    start_pandas_profiling_report(df, rep_folder, rep_file_name, pp_max_sample)
  File "C:\Users\groshev3-vn\Documents\20210215 backend_test\pmprofiler\profiler.py", line 296, in start_pandas_profiling_report
    pandas_profiling.ProfileReport(dfp).to_file(pand_prof_name)
  File "c:\anaconda3\lib\site-packages\pandas_profiling\__init__.py", line 70, in __init__
    description_set = describe_df(df)
  File "c:\anaconda3\lib\site-packages\pandas_profiling\model\describe.py", line 602, in describe
    executor.imap_unordered(multiprocess_1d, args)
  File "c:\anaconda3\lib\multiprocessing\pool.py", line 735, in next
    raise value
  File "c:\anaconda3\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "c:\anaconda3\lib\site-packages\pandas_profiling\model\describe.py", line 388, in multiprocess_1d
    return column, describe_1d(series)
  File "c:\anaconda3\lib\site-packages\pandas_profiling\model\describe.py", line 368, in describe_1d
    type_to_func[series_description["type"]](series, series_description)
  File "c:\anaconda3\lib\site-packages\pandas_profiling\model\describe.py", line 167, in describe_categorical_1d
    stats.update(text_summary(series))
  File "c:\anaconda3\lib\site-packages\visions\application\summaries\series\text_summary.py", line 30, in text_summary
    summary["script_values"] = {key: script(key) for key in character_counts.keys()}
  File "c:\anaconda3\lib\site-packages\visions\application\summaries\series\text_summary.py", line 30, in <dictcomp>
    summary["script_values"] = {key: script(key) for key in character_counts.keys()}
  File "c:\anaconda3\lib\site-packages\tangled_up_in_unicode\tangled_up_in_unicode.py", line 413136, in script
    key_end = end_keys[insertion_point]
IndexError: list index out of range
```
Out of all data I was to find the cell with data that produces this error (See attached csv file).
I use **Python 3.6**, **pip**, and both **win10** and **RHLinux**. The same error occurs no matter run it in a command shell or Jupyter Notebook.

As I understood, this the only last character is the reason. Original data are in UTF-8.

**Comment by vgroshev** [comment]
[pip_freeze_win10.txt](https://github.com/pandas-profiling/pandas-profiling/files/6009448/pip_freeze_win10.txt)
[pip_freeze_linux.txt](https://github.com/pandas-profiling/pandas-profiling/files/6009449/pip_freeze_linux.txt)

**Comment by vgroshev** [comment]
[only7_union_comma.txt](https://github.com/pandas-profiling/pandas-profiling/files/6009468/only7_union_comma.txt)

**Comment by sbrugman** [comment]
Good point, the character-level analysis assumes utf-8. Quick fix would be to turn that off (see config docs). 

Needs a fix. Feel free to send in a PR.

**Comment by vgroshev** [comment]
Thank for your reply, I don't feel I understand what and how to fix in the code though.

**Comment by sbrugman** [comment]
The issue is actually with [tangled-up-in-unicode](https://github.com/dylan-profiler/tangled-up-in-unicode):

```python
from tangled_up_in_unicode import script

character = "􀉆"
script(character)
```

**Comment by Zalfrin** [comment]
As a temporary workaround until tangled_up_in_unicode gets fixed, I found I could get past this error on my dataset by using:

report = ProfileReport(df, vars={'cat':{'characters':False}})

The advanced usage documentation page mentioned vars.cat.unicode, but it doesn't seem like this option exists in the latest release of pandas-profiling.

**Comment by vgroshev** [comment]
Hi. Are you planning to update package at https://pypi.org/project/tangled-up-in-unicode/ also? (It would be really cool:)

**Comment by sbrugman** [comment]
@vgroshev Just updated the tangled-up-in-unicode package, let me know if that resolves your problem. 

_ps. This project is maintained on best-effort basis, you are very welcome to [support it](https://github.com/sponsors/sbrugman)._
