### ISSUE TITLE
Can't create reports from dataframes using newer/nullable dtypes

### ISSUE THREAD

**Issue by mands** [pandas-profiling/pandas-profiling#812]
**Describe the bug**

When using a dataframe with newwe dtypes, such as the following, I am unable to generate any reports

```python
In[83]: df4.dtypes
Out[83]: 
str_col       string
int_col        Int64
float_col    Float64
uint_col       UInt8
dtype: object

In[84]: ProfileReport(df, title="Pandas Profiling Report", minimal=True, progress_bar=False, lazy=False)
Traceback (most recent call last):
  File "/project/.venv/lib64/python3.9/site-packages/pandas/core/arrays/integer.py", line 126, in safe_cast
    return values.astype(dtype, casting="safe", copy=copy)
TypeError: Cannot cast array data from dtype('O') to dtype('int64') according to the rule 'safe'
...
```

The exact error varies depending on which column it has tried to convert first, e.g. I can get the following too,
```python
TypeError: Cannot cast array data from dtype('O') to dtype('uint8') according to the rule 'safe'
OR
  File "pandas/_libs/algos.pyx", line 292, in pandas._libs.algos.__pyx_fused_cpdef
TypeError: No matching signature found
```

**To Reproduce**

_Data:_
Included in code-snippet below, df.info as follows

```python
df.info()
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   str_col    30 non-null     string 
 1   int_col    30 non-null     Int64  
 2   float_col  30 non-null     Float64
 3   uint_col   30 non-null     UInt8  
dtypes: Float64(1), Int64(1), UInt8(1), string(1)
memory usage: 968.0 bytes
```

_Code:_ 
```python
"""
Test for issue XXX:
https://github.com/pandas-profiling/pandas-profiling/issues/XXX
"""
import pandas as pd
from pandas_profiling import ProfileReport

def test_issueXXX():
    df = pd.DataFrame(
        dict(
            str_col=[f"str-{x}" for x in range(30)],
            int_col=[x for x in range(30)],
            float_col=[(x + 0.1) for x in range(30)],
            uint_col=[x for x in range(30)],
        ))

    df["uint_col"] = pd.to_numeric(df["uint_col"], downcast="unsigned")
    df = df.convert_dtypes()
    ProfileReport(df, title="Pandas Profiling Report", minimal=True, progress_bar=False, lazy=False)


```

**Version information:**

* _Python version_: 3.9.6
* _OS_: Linux 64bit (Fedora 34)
* _Environment_: PyCharm and commandline
* _pandas_profiling version_: 3.0.0 (have noticed on 2.x series also)
* _pandas version_: 1.3.1
* _`pip`_: Using poetry, output of `poetry show` below

<details><summary>Click to expand <strong><em>Version information</em></strong></summary>
<p>

```
altair                          4.1.0               Altair: A declarative statistical visualization library for Python.
amqp                            5.0.6               Low-level AMQP client for Python (fork of amqplib).
appdirs                         1.4.4               A small Python module for determining appropriate platform-specific dirs, e.g. a "user data dir".
argon2-cffi                     20.1.0              The secure Argon2 password hashing algorithm.
asgiref                         3.4.1               ASGI specs, helper code, and adapters
async-generator                 1.10                Async generators and context managers for Python 3.5+
attrs                           21.2.0              Classes Without Boilerplate
backcall                        0.2.0               Specifications for callback functions passed in to an API
backoff                         1.11.1              Function decoration for backoff and retry
billiard                        3.6.4.0             Python multiprocessing fork with improvements and bugfixes
bleach                          3.3.1               An easy safelist-based HTML-sanitizing tool.
bokeh                           2.2.3               Interactive plots and applications in the browser from Python
boltons                         20.2.1              When they're not builtins, they're boltons.
boto3                           1.18.8              The AWS SDK for Python
botocore                        1.21.8              Low-level, data-driven core of boto 3.
bottleneck                      1.3.2               Fast NumPy array functions written in C
branca                          0.4.2               Generate complex HTML+JS pages with Python
brotli                          1.0.9               Python bindings for the Brotli compression library
cachetools                      4.2.2               Extensible memoizing collections and decorators
celery                          5.1.2               Distributed Task Queue.
certifi                         2021.5.30           Python package for providing Mozilla's CA Bundle.
cffi                            1.14.6              Foreign Function Interface for Python calling C code.
chardet                         4.0.0               Universal encoding detector for Python 2 and 3
charset-normalizer              2.0.3               The Real First Universal Charset Detector. Open, modern and actively maintained alternative to Chardet.
click                           7.1.2               Composable command line interface toolkit
click-didyoumean                0.0.3               Enable git-like did-you-mean feature in click.
click-plugins                   1.1.1               An extension module for click to enable registering CLI commands via setuptools entry-points.
click-repl                      0.2.0               REPL plugin for Click
click-spinner                   0.1.10              Spinner for Click
colorama                        0.4.4               Cross-platform colored terminal text.
colorlog                        4.8.0               Log formatting with colors!
commonmark                      0.9.1               Python parser for the CommonMark Markdown spec
coreapi                         2.3.3               Python client library for Core API.
coreschema                      0.0.4               Core Schema.
crispy-tailwind                 0.5.0               A tailwind package for Django Crispy Forms
croniter                        1.0.15              croniter provides iteration for datetime object with cron like format
cryptography                    3.4.7               cryptography is a package which provides cryptographic recipes and primitives to Python developers.
cycler                          0.10.0              Composable style cycles
dacite                          1.6.0               Simple creation of data classes from dictionaries.
datacommons                     1.4.3               A library to access Data Commons Python API.
datacommons-pandas              0.0.3               A library to create pandas objects using the Data Commons Python API.
decorator                       5.0.9               Decorators for Humans
defusedxml                      0.7.1               XML bomb protection for Python stdlib modules
dj-database-url                 0.5.0               Use Database URLs in your Django Application.
dj-email-url                    1.0.2               Use an URL to configure email backend settings in your Django Application.
django                          3.1.13              A high-level Python Web framework that encourages rapid development and clean, pragmatic design.
django-activity-stream          0.10.0              Generate generic activity streams from the actions on your site. Users can follow any actors' activities for personalized streams.
django-allauth                  0.45.0              Integrated set of Django applications addressing authentication, registration, account management as well as 3rd party (social) account authen...
django-appconf                  1.0.4               A helper class for handling configuration defaults of packaged apps gracefully.
django-braces                   1.14.0              Reusable, generic mixins for Django
django-celery-beat              2.2.1               Database-backed Periodic Tasks.
django-celery-email             3.0.0               An async Django email backend using celery
django-components               0.12                A way to create simple reusable template components in Django.
django-configurations           2.2                 A helper for organizing Django settings.
django-contrib-comments         2.1.0               The code formerly known as django.contrib.comments.
django-crispy-forms             1.12.0              Best way to have Django DRY forms
django-debug-toolbar            3.2.1               A configurable set of panels that display various debug information about the current request/response.
django-dynamic-preferences      1.10.1              Dynamic global and instance settings for your django project
django-etc                      1.3.0               Tiny stuff for Django that won't fit into separate apps.
django-extensions               3.1.3               Extensions for Django
django-extra-views              0.14.0              Extra class-based views for Django
django-filter                   2.4.0               Django-filter is a reusable Django application for allowing users to filter querysets dynamically.
django-friendly-tag-loader      1.3.1               Want to optionally use a template tag library? Use this!
django-fullurl                  1.1                 Adds three template tags to Django: `fullurl`, `fullstatic` and `buildfullurl`. The template tag `fullurl` acts just like `url`, but it always...
django-hashid-field             3.2.1               A Hashids obfuscated Django Model Field
django-herald                   0.2.1               Django library for separating the message content from transmission method
django-hitcount                 1.3.3               Hit counting application for Django.
django-invitations              1.9.3               Generic invitations app with support for django-allauth
django-likes                    2.0.1               Django app providing view interface to django-secretballot.
django-log-request-id           1.6.0               Django middleware and log filter to attach a unique ID to every log message generated as part of a request
django-maintenance-mode         0.16.0              django-maintenance-mode shows a 503 error page when maintenance-mode is on.
django-meta                     2.0.0               Pluggable app for handling webpage meta tags and OpenGraph properties
django-pygments                 0.4                 A django app that provides a template tag and 2 filters for                 doing syntax highlighting with Pygments
django-react-templatetags       6.0.2               This django library allows you to add React components into your django templates.
django-recaptcha                2.0.6               Django recaptcha form field/widget app.
django-redis                    5.0.0               Full featured redis cache backend for Django.
django-sameas                   0.1.0 9c6a2de       
django-secretballot             2.0.0-dev2 3cd1f56  
django-service-objects          0.7.0               Service objects for Django
django-settings-export          1.2.1               This Django app allows you to export certain settings to your templates.
django-storages                 1.11.1              Support for many storage backends in Django
django-stubs                    1.8.0               Mypy stubs for Django
django-stubs-ext                0.2.0               Monkey-patching and extensions for django-stubs
django-taggit                   1.5.1               django-taggit is a reusable Django application for simple tagging.
django-taggit-serializer        0.1.7               The Django Taggit serializer for tDjango REST Framework
django-template-block-args      0.0.5               
django-timezone-field           4.2.1               A Django app providing database and form fields for pytz timezone objects.
django-tz-detect                0.3.0               Automatic user timezone detection for django
django-waffle                   2.2.1               A feature flipper for Django.
django-watchman                 1.2.0               django-watchman exposes a status endpoint for your backing services
django-widget-tweaks            1.4.8               Tweak the form field rendering in templates, not in python-level form definitions.
django-xml                      3.0.0               Provides an abstraction to lxml's XPath and XSLT functionality in a manner resembling django database models
djangorestframework             3.12.4              Web APIs for Django, made easy.
djangorestframework-dataclasses 0.10                A dataclasses serializer for Django REST Framework
djangorestframework-stubs       1.4.0               PEP-484 stubs for django-rest-framework
docker-image-py                 0.1.12              Parse docker image as distribution does.
dominate                        2.6.0               Dominate is a Python library for creating and manipulating HTML documents using an elegant DOM API.
drf-extensions                  0.7.0               Extensions for Django REST Framework
entrypoints                     0.3                 Discover and load entry points from installed packages.
environs                        9.3.2               simplified environment variable parsing
et-xmlfile                      1.1.0               An implementation of lxml.xmlfile for the standard library
face                            20.1.1              A command-line application framework (and CLI parser). Friendly for users, full-featured for developers.
factory-boy                     3.2.0               A versatile test fixtures replacement based on thoughtbot's factory_bot for Ruby.
faker                           8.10.3              Faker is a Python package that generates fake data for you.
flake8                          3.9.2               the modular source code checker: pep8 pyflakes and co
flit-core                       3.0.0               Distribution-building parts of Flit. See flit package for more information
folium                          0.12.1              Make beautiful maps with Leaflet.js & Python
furl                            2.1.2               URL manipulation made simple.
glom                            20.11.0             A declarative object transformer and formatter, for conglomerating nested data.
google-api-core                 1.31.1              Google API client core library
google-auth                     1.34.0              Google Authentication Library
google-cloud-core               1.7.2               Google Cloud API client core library
google-cloud-storage            1.41.1              Google Cloud Storage API client library
google-crc32c                   1.1.2               A python wrapper of the C library 'Google CRC32C'
google-resumable-media          1.3.1               Utilities for Google Media Downloads and Resumable Uploads
googleapis-common-protos        1.53.0              Common protobufs used in Google APIs
gunicorn                        20.1.0              WSGI HTTP Server for UNIX
hashids                         1.3.1               Implements the hashids algorithm in python. For more information, visit http://hashids.org/
htmlmin                         0.1.12              An HTML Minifier
idna                            3.2                 Internationalized Domain Names in Applications (IDNA)
imagehash                       4.2.1               Image Hashing library
importlib-resources             5.2.0               Read resources from Python packages
iniconfig                       1.1.1               iniconfig: brain-dead simple config-ini parsing
ipython                         7.25.0              IPython: Productive Interactive Computing
ipython-genutils                0.2.0               Vestigial utilities from IPython
itypes                          1.2.0               Simple immutable types for python.
jedi                            0.18.0              An autocompletion tool for Python that can be used for text editors.
jinja2                          3.0.1               A very fast and expressive template engine.
jmespath                        0.10.0              JSON Matching Expressions
joblib                          1.0.1               Lightweight pipelining with Python functions
jsonpickle                      2.0.0               Python library for serializing any arbitrary object graph into JSON
jsonschema                      3.2.0               An implementation of JSON Schema validation for Python
jupyter-client                  6.2.0               Jupyter protocol implementation and client libraries
jupyter-core                    4.7.1               Jupyter core package. A base package on which Jupyter projects rely.
jupyterlab-pygments             0.1.2               Pygments theme using JupyterLab CSS variables
kiwisolver                      1.3.1               A fast implementation of the Cassowary constraint solver
kombu                           5.1.0               Messaging library for Python.
libgravatar                     1.0.0               A library that provides a Python 3 interface for the Gravatar API.
lxml                            4.6.3               Powerful and Pythonic XML processing library combining libxml2/libxslt with the ElementTree API.
lz4                             3.1.3               LZ4 Bindings for Python
markdown                        3.3.4               Python implementation of Markdown.
markupsafe                      2.0.1               Safely add untrusted strings to HTML/XML markup.
marshmallow                     3.13.0              A lightweight library for converting complex datatypes to and from native Python datatypes.
martor                          1.6.4               Django Markdown Editor
matplotlib                      3.4.2               Python plotting package
matplotlib-inline               0.1.2               Inline Matplotlib backend for Jupyter
mccabe                          0.6.1               McCabe checker, plugin for flake8
micawber                        0.5.4               a small library for extracting rich content from urls
missingno                       0.5.0               Missing data visualization module for Python.
mistune                         0.8.4               The fastest markdown parser in pure Python
monotonic                       1.6                 An implementation of time.monotonic() for Python 2 & < 3.3
mslex                           0.3.0               shlex for windows
multimethod                     1.4                 Multiple argument dispatching.
munch                           2.5.0               A dot-accessible dictionary (a la JavaScript objects)
mypy                            0.800               Optional static typing for Python
mypy-extensions                 0.4.3               Experimental type system extensions for programs checked with the mypy typechecker.
nbclient                        0.5.3               A client library for executing notebooks. Formerly nbconvert's ExecutePreprocessor.
nbconvert                       6.1.0               Converting Jupyter Notebooks
nbformat                        5.1.3               The Jupyter Notebook format
nest-asyncio                    1.5.1               Patch asyncio to allow nested event loops
networkx                        2.6.2               Python package for creating and manipulating graphs and networks
numpy                           1.21.1              NumPy is the fundamental package for array computing with Python.
oauthlib                        3.1.1               A generic, spec-compliant, thorough implementation of the OAuth request-signing logic
openpyxl                        3.0.7               A Python library to read/write Excel 2010 xlsx/xlsm files
orderedmultidict                1.0.1               Ordered Multivalue Dictionary
packaging                       20.9                Core utilities for Python packages
pandas                          1.3.1               Powerful data structures for data analysis, time series, and statistics
pandas-profiling                3.0.0               Generate profile report for pandas DataFrame
pandocfilters                   1.4.3               Utilities for writing pandoc filters in python
parso                           0.8.2               A Python Parser
persisting-theory               0.2.1               Registries that can autodiscover values accross your project apps
pexpect                         4.8.0               Pexpect allows easy control of interactive console applications.
phik                            0.12.0              Phi_K correlation analyzer library
pickleshare                     0.7.5               Tiny 'shelve'-like database with concurrency support
pillow                          8.3.1               Python Imaging Library (Fork)
plotly                          4.14.3              An open-source, interactive data visualization library for Python
pluggy                          0.13.1              plugin and hook calling mechanisms for python
posthog                         1.4.2               Integrate PostHog into any python application.
prompt-toolkit                  3.0.19              Library for building powerful interactive command lines in Python
protobuf                        3.17.3              Protocol Buffers
psutil                          5.8.0               Cross-platform lib for process and system monitoring in Python.
psycopg2-binary                 2.9.1               psycopg2 - Python-PostgreSQL Database Adapter
ptyprocess                      0.7.0               Run a subprocess in a pseudo terminal
py                              1.10.0              library with cross-python path, ini-parsing, io, code, log facilities
pyarrow                         3.0.0               Python library for Apache Arrow
pyasn1                          0.4.8               ASN.1 types and codecs
pyasn1-modules                  0.2.8               A collection of ASN.1-based protocols modules.
pycodestyle                     2.7.0               Python style guide checker
pycparser                       2.20                C parser in Python
pydantic                        1.8.2               Data validation and settings management using python 3.6 type hinting
pyee                            8.1.0               A port of node.js's EventEmitter to python.
pyflakes                        2.3.1               passive checker of Python programs
pygments                        2.9.0               Pygments is a syntax highlighting package written in Python.
pyjwt                           2.1.0               JSON Web Token implementation in Python
pyparsing                       2.4.7               Python parsing module
pyppeteer                       0.2.5               Headless chrome/chromium automation library (unofficial port of puppeteer)
pyrsistent                      0.18.0              Persistent/Functional/Immutable data structures
pytest                          6.2.4               pytest: simple powerful testing with Python
pytest-datadir                  1.3.1               pytest plugin for test data directories and files
python-crontab                  2.5.1               Python Crontab API
python-dateutil                 2.8.2               Extensions to the standard Python datetime module
python-dotenv                   0.19.0              Read key-value pairs from a .env file and set them as environment variables
python-json-logger              2.0.2               A python library adding a json log formatter
python3-openid                  3.2.0               OpenID support for modern servers and consumers.
pytoml                          0.1.21              A parser for TOML-0.4.0
pytz                            2021.1              World timezone definitions, modern and historical
pywatchman                      1.4.1               Watchman client for python
pywavelets                      1.1.1               PyWavelets, wavelet transform module
pyyaml                          5.4.1               YAML parser and emitter for Python
pyzmq                           22.1.0              Python bindings for 0MQ
ratelimitingfilter              1.2                 A rate limiting filter for the Python logging system
redis                           3.5.3               Python client for Redis key-value store
regex                           2021.7.6            Alternative regular expression module, to replace re.
requests                        2.26.0              Python HTTP for Humans.
requests-oauthlib               1.3.0               OAuthlib authentication support for Requests.
requests-toolbelt               0.9.1               A utility belt for advanced users of python-requests
retrying                        1.3.3               Retrying
rsa                             4.7.2               Pure-Python RSA implementation
rules                           2.2                 Awesome Django authorization, without the database
s3transfer                      0.5.0               An Amazon S3 Transfer Manager
scipy                           1.7.0               SciPy: Scientific Library for Python
seaborn                         0.11.1              seaborn: statistical data visualization
six                             1.16.0              Python 2 and 3 compatibility utilities
snakeviz                        2.1.0               A web-based viewer for Python profiler output
sqlparse                        0.4.1               A non-validating SQL parser.
stringcase                      1.2.0               String case converter.
stripe                          2.60.0              Python bindings for the Stripe API
tabulate                        0.8.9               Pretty-print tabular data
tangled-up-in-unicode           0.1.0               Access to the Unicode Character Database (UCD)
taskipy                         1.8.1               tasks runner for python projects
testpath                        0.5.0               Test utilities for code working with files and commands
text-unidecode                  1.3                 The most basic Text::Unidecode port
toml                            0.10.2              Python Library for Tom's Obvious, Minimal Language
toolz                           0.11.1              List processing tools and functional utilities
tornado                         6.1                 Tornado is a Python web framework and asynchronous networking library, originally developed at FriendFeed.
tqdm                            4.61.2              Fast, Extensible Progress Meter
traitlets                       5.0.5               Traitlets Python configuration system
typed-ast                       1.4.3               a fork of Python 2 and 3 ast modules with type comment support
typing-extensions               3.10.0.0            Backported and Experimental Type Hints for Python 3.5+
unittest-xml-reporting          3.0.4               unittest-based test runner with Ant/JUnit like XML reporting.
uritemplate                     3.0.1               URI templates
urllib3                         1.26.6              HTTP library with thread-safe connection pooling, file post, and more.
validators                      0.18.2              Python Data Validation for Humans™.
vine                            5.0.0               Promises, promises, promises.
visions                         0.7.1               Visions
wcwidth                         0.2.5               Measures the displayed width of unicode strings in a terminal
webencodings                    0.5.1               Character encoding aliases for legacy web content
websockets                      8.1                 An implementation of the WebSocket Protocol (RFC 6455 & 7692)
whitenoise                      5.3.0               Radically simplified static file serving for WSGI applications
zipp                            3.5.0               Backport of pathlib-compatible object wrapper for zip files

```

</p>
</details>

**Comment by gwen47** [comment]
For me I can generate the report, but at least the pandas nullable integer are consider in the report as Categorical because they are object. Real type `'Condition_importance': dtype(pd.UInt8Dtype)`


![image](https://user-images.githubusercontent.com/34361978/143724129-ac894278-ba18-4045-b736-cc7e1a696f3f.png)
![image](https://user-images.githubusercontent.com/34361978/143724250-d906db16-d5ed-4266-92e7-aa370575d2a7.png)

#### Version information:
- Python version: 3.7.10 
- OS: Linux 
- Environment: notebook kaggle
- pandas version: 1.3.3

**Comment by sbrugman** [comment]
@gwen47 Great catch, this should be solved in the type system. Please open another issue (the two are related but independent)
