### ISSUE TITLE
RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by gnomic** [pandas-profiling/pandas-profiling#84]
This is an 18k file with 105 columns that never completes. Works on other files.

RecursionError: maximum recursion depth exceeded while calling a Python object[I 23:07:36.416 

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.3.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 69 Stepping 1, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.21.0
pytest: 3.3.0
pip: 9.0.1
setuptools: 36.5.0.post20170921
Cython: 0.27.3
numpy: 1.13.3
scipy: 1.0.0
pyarrow: None
xarray: 0.10.0
IPython: 6.2.1
sphinx: 1.6.3
patsy: 0.4.1
dateutil: 2.6.1
pytz: 2017.3
blosc: None
bottleneck: 1.2.1
tables: 3.4.2
numexpr: 2.6.4
feather: None
matplotlib: 2.1.1
openpyxl: 2.4.9
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.0.2
lxml: 4.1.1
bs4: 4.6.0
html5lib: 1.0.1
sqlalchemy: 1.1.13
pymysql: None
psycopg2: 2.7.3.1 (dt dec pq3 ext lo64)
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

Error shown (as much as I could capture)

  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 2277, in _replace_single
    mgr=mgr)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 771, in replace
    filter=filter, regex=regex, convert=convert)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 2236, in replace
    regex=regex, mgr=mgr)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 2277, in _replace_single
    mgr=mgr)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 771, in replace
    filter=filter, regex=regex, convert=convert)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 2236, in replace
    regex=regex, mgr=mgr)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 2277, in _replace_single
    mgr=mgr)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 771, in replace
    filter=filter, regex=regex, convert=convert)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 2236, in replace
    regex=regex, mgr=mgr)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 2277, in _replace_single
    mgr=mgr)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 771, in replace
    filter=filter, regex=regex, convert=convert)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 2236, in replace
    regex=regex, mgr=mgr)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 2277, in _replace_single
    mgr=mgr)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 771, in replace
    filter=filter, regex=regex, convert=convert)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 2236, in replace
    regex=regex, mgr=mgr)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 2277, in _replace_single
    mgr=mgr)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 771, in replace
    filter=filter, regex=regex, convert=convert)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 2236, in replace
    regex=regex, mgr=mgr)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 2277, in _replace_single
    mgr=mgr)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 771, in replace
    filter=filter, regex=regex, convert=convert)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 2236, in replace
    regex=regex, mgr=mgr)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 2277, in _replace_single
    mgr=mgr)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 771, in replace
    filter=filter, regex=regex, convert=convert)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 2236, in replace
    regex=regex, mgr=mgr)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 2277, in _replace_single
    mgr=mgr)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 771, in replace
    filter=filter, regex=regex, convert=convert)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 2236, in replace
    regex=regex, mgr=mgr)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 2277, in _replace_single
    mgr=mgr)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 771, in replace
    filter=filter, regex=regex, convert=convert)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 2236, in replace
    regex=regex, mgr=mgr)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 2277, in _replace_single
    mgr=mgr)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 771, in replace
    filter=filter, regex=regex, convert=convert)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 2236, in replace
    regex=regex, mgr=mgr)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 2277, in _replace_single
    mgr=mgr)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 771, in replace
    filter=filter, regex=regex, convert=convert)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 2236, in replace
    regex=regex, mgr=mgr)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 2277, in _replace_single
    mgr=mgr)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 771, in replace
    filter=filter, regex=regex, convert=convert)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 2236, in replace
    regex=regex, mgr=mgr)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 2277, in _replace_single
    mgr=mgr)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 771, in replace
    filter=filter, regex=regex, convert=convert)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 2236, in replace
    regex=regex, mgr=mgr)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 2277, in _replace_single
    mgr=mgr)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 771, in replace
    filter=filter, regex=regex, convert=convert)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 2236, in replace
    regex=regex, mgr=mgr)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 2277, in _replace_single
    mgr=mgr)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 771, in replace
    filter=filter, regex=regex, convert=convert)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 2236, in replace
    regex=regex, mgr=mgr)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 2277, in _replace_single
    mgr=mgr)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 771, in replace
    filter=filter, regex=regex, convert=convert)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 2236, in replace
    regex=regex, mgr=mgr)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 2277, in _replace_single
    mgr=mgr)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 771, in replace
    filter=filter, regex=regex, convert=convert)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 2236, in replace
    regex=regex, mgr=mgr)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 2277, in _replace_single
    mgr=mgr)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 771, in replace
    filter=filter, regex=regex, convert=convert)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 2236, in replace
    regex=regex, mgr=mgr)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 2277, in _replace_single
    mgr=mgr)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 771, in replace
    filter=filter, regex=regex, convert=convert)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 2236, in replace
    regex=regex, mgr=mgr)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 2277, in _replace_single
    mgr=mgr)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 771, in replace
    filter=filter, regex=regex, convert=convert)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 2236, in replace
    regex=regex, mgr=mgr)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 2277, in _replace_single
    mgr=mgr)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 771, in replace
    filter=filter, regex=regex, convert=convert)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 2236, in replace
    regex=regex, mgr=mgr)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 2277, in _replace_single
    mgr=mgr)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 771, in replace
    filter=filter, regex=regex, convert=convert)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 2236, in replace
    regex=regex, mgr=mgr)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 2277, in _replace_single
    mgr=mgr)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 771, in replace
    filter=filter, regex=regex, convert=convert)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 2236, in replace
    regex=regex, mgr=mgr)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 2277, in _replace_single
    mgr=mgr)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\internals.py", line 755, in replace
    mask = missing.mask_missing(values, to_replace)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\missing.py", line 31, in mask_missing
    dtype, values_to_mask = infer_dtype_from_array(values_to_mask)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\dtypes\cast.py", line 467, in infer_dtype_from_array
    if not is_list_like(arr):
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\site-packages\p
andas\core\dtypes\inference.py", line 266, in is_list_like
    return (isinstance(obj, Iterable) and
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\abc.py", line 1
82, in __instancecheck__
    if subclass in cls._abc_cache:
RecursionError: maximum recursion depth exceeded

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\multiprocessing
\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\multiprocessing
\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\multiprocessing
\pool.py", line 122, in worker
    e = ExceptionWithTraceback(e, e.__traceback__)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\multiprocessing
\pool.py", line 61, in __init__
    tb = traceback.format_exception(type(exc), exc, tb)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\traceback.py",
line 117, in format_exception
    type(value), value, tb, limit=limit).format(chain=chain))
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\traceback.py",
line 486, in __init__
    _seen=_seen)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\traceback.py",
line 486, in __init__
    _seen=_seen)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\traceback.py",
line 486, in __init__
    _seen=_seen)
  [Previous line repeated 242 more times]
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\traceback.py",
line 480, in __init__
    type(exc_value.__context__),
RecursionError: maximum recursion depth exceeded while calling a Python object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\multiprocessing
\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\multiprocessing
\spawn.py", line 118, in _main
    return self._bootstrap()
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\multiprocessing
\process.py", line 274, in _bootstrap
    traceback.print_exc()
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\traceback.py",
line 159, in print_exc
    print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\traceback.py",
line 100, in print_exception
    type(value), value, tb, limit=limit).format(chain=chain):
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\traceback.py",
line 486, in __init__
    _seen=_seen)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\traceback.py",
line 486, in __init__
    _seen=_seen)
  File "C:\Users\123456789\AppData\Local\Continuum\Anaconda3\lib\traceback.py",
line 486, in __init__
    _seen=_seen)
  [Previous line repeated 244 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by conradoqg** [comment]
Hey,

Could you get the beginning of the stacktrace (before the repeated part)? Preferably one that shows in the file name some of the source files of the pandas-profiling?

Also if you can try with the "check_correlation = False", I appreciate that.

Thank you

**Comment by JosPolfliet** [comment]
@conradoqg would it make sense to change the default of `check_correlation` to `False`. For big datasets, the value it brings might not be worth the performance and stability problems it introduces.

**Comment by conradoqg** [comment]
@JosPolfliet I think the heavy part is the recoded check. In the PR #82 I introduced the check_recoded parameter to disable this feature. In my opinion, we should turn this False by default.

What do you think?

**Comment by gnomic** [comment]
Where exactly do I set check_correlation to false? I can't find an example of how any of the variables are set.  There was a glitch in the excel file that put a autoassigned column name ("column12834") at the top of every column after my data - never saw that happen before.  That seems to be what was causing it to crash. So once I got the 108x18039 file that I expected, it gets to the profile statement and never returns.  No errors, it just never completes.

**Comment by conradoqg** [comment]
Hey

We're improving this right now and probably the next release 1.4.1 will have this issue solved.

The release 1.4 doesn't have the `check_correlation` either the `check_recoded` parameters (this is the guy that usually freezes the profiling)

Best

**Comment by gnomic** [comment]
But where do I set check_recorded? Can you give me an example? 

Also, Thanks for all the help! I'm happy to test anything you toss my way.

**Comment by conradoqg** [comment]
Hey

We just released the 1.4.1 with that parameter set to false by default. Could you check again to see if it works using that release?

By default in 1.4.1 the `check_correlation` is set to `True` but `check_recoded` is set to `False` which should solve a lot of problems.

To change those parameters you can do this:
`pfr = pandas_profiling.ProfileReport(df, check_correlation = False)` (to disable the correlation at all)
or
`pfr = pandas_profiling.ProfileReport(df, check_recoded = True)` (to calculate the recoded, which is very heavy and can cause the problem you sent)

Best

**Comment by gnomic** [comment]
Upgraded to 1.41 and tried every variation on just 5000 records of 108 fields

p = pandas_profiling.ProfileReport(untested, check_correlation = False, check_recoded = True)

It just starts and never completed (up to 14 hours runtime). Is there some way to log what is happening?

**Comment by andrewsali** [comment]
We had a similar issue and downgrading pandas to 0.20.3 resolved it. Potentially related to the following? https://stackoverflow.com/questions/47791164/pandas-0-21-1-dataframe-replace-recursion-error

**Comment by leehonan** [comment]
I found that this was caused by a large dataframe (12M rows) with ridiculous datetime column values (e.g. 900 AD, 2900 AD).  I tried messing around with sys.setrecursionlimit() but even with 32GB of RAM would run out of memory.  Dropping the datetime columns out sorted it.
