### ISSUE TITLE
Cant install pandas

### ISSUE THREAD

**Issue by anajulialuizon** [pandas-profiling/pandas-profiling#912]
Just installed python for the first time today. I keep getting this error when trying to install panda
![image](https://user-images.githubusercontent.com/91978229/150871967-28eeaf3d-c817-4ebc-839d-0f028dc8d9c0.png)
What should I do?

**Comment by mcastellino** [comment]
I have the same problem,...

`PS C:\Users\mcast> pip install -U pandas-profiling[notebook]
Collecting pandas-profiling[notebook]
  Using cached pandas_profiling-3.1.0-py2.py3-none-any.whl (261 kB)
Collecting PyYAML>=5.0.0
  Using cached PyYAML-6.0-cp310-cp310-win_amd64.whl (151 kB)
Collecting multimethod>=1.4
  Using cached multimethod-1.7-py3-none-any.whl (9.5 kB)
Collecting htmlmin>=0.1.12
  Using cached htmlmin-0.1.12-py3-none-any.whl
Collecting tqdm>=4.48.2
  Using cached tqdm-4.62.3-py2.py3-none-any.whl (76 kB)
Collecting pydantic>=1.8.1
  Using cached pydantic-1.9.0-cp310-cp310-win_amd64.whl (2.1 MB)
Requirement already satisfied: matplotlib>=3.2.0 in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from pandas-profiling[notebook]) (3.5.1)
Collecting visions[type_image_path]==0.7.4
  Using cached visions-0.7.4-py3-none-any.whl (102 kB)
Requirement already satisfied: requests>=2.24.0 in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from pandas-profiling[notebook]) (2.26.0)
Requirement already satisfied: jinja2>=2.11.1 in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from pandas-profiling[notebook]) (3.0.2)
Requirement already satisfied: numpy>=1.16.0 in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from pandas-profiling[notebook]) (1.22.1)
Collecting missingno>=0.4.2
  Using cached missingno-0.5.0-py3-none-any.whl (8.8 kB)
Collecting tangled-up-in-unicode==0.1.0
  Using cached tangled_up_in_unicode-0.1.0-py3-none-any.whl (3.1 MB)
Collecting joblib~=1.0.1
  Using cached joblib-1.0.1-py3-none-any.whl (303 kB)
Collecting phik>=0.11.1
  Using cached phik-0.12.0.tar.gz (44 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: markupsafe~=2.0.1 in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from pandas-profiling[notebook]) (2.0.1)
Collecting scipy>=1.4.1
  Using cached scipy-1.8.0-cp310-cp310-win_amd64.whl (37.0 MB)
Requirement already satisfied: pandas!=1.0.0,!=1.0.1,!=1.0.2,!=1.1.0,>=0.25.3 in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from pandas-profiling[notebook]) (1.4.0)
Collecting seaborn>=0.10.1
  Using cached seaborn-0.11.2-py3-none-any.whl (292 kB)
Collecting ipywidgets>=7.5.1
  Using cached ipywidgets-7.6.5-py2.py3-none-any.whl (121 kB)
Requirement already satisfied: jupyter-core>=4.6.3 in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from pandas-profiling[notebook]) (4.9.1)
Requirement already satisfied: jupyter-client>=6.0.0 in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from pandas-profiling[notebook]) (7.0.6)
Requirement already satisfied: attrs>=19.3.0 in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from visions[type_image_path]==0.7.4->pandas-profiling[notebook]) (21.2.0)
Collecting networkx>=2.4
  Using cached networkx-2.6.3-py3-none-any.whl (1.9 MB)
Requirement already satisfied: Pillow in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from visions[type_image_path]==0.7.4->pandas-profiling[notebook]) (9.0.1)
Collecting imagehash
  Using cached ImageHash-4.2.1-py2.py3-none-any.whl
Requirement already satisfied: ipython-genutils~=0.2.0 in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from ipywidgets>=7.5.1->pandas-profiling[notebook]) (0.2.0)
Collecting jupyterlab-widgets>=1.0.0
  Using cached jupyterlab_widgets-1.0.2-py3-none-any.whl (243 kB)
Collecting widgetsnbextension~=3.5.0
  Using cached widgetsnbextension-3.5.2-py2.py3-none-any.whl (1.6 MB)
Requirement already satisfied: traitlets>=4.3.1 in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from ipywidgets>=7.5.1->pandas-profiling[notebook]) (5.1.1)
Requirement already satisfied: ipython>=4.0.0 in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from ipywidgets>=7.5.1->pandas-profiling[notebook]) (7.29.0)
Requirement already satisfied: nbformat>=4.2.0 in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from ipywidgets>=7.5.1->pandas-profiling[notebook]) (5.1.3)
Requirement already satisfied: ipykernel>=4.5.1 in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from ipywidgets>=7.5.1->pandas-profiling[notebook]) (6.5.0)
Requirement already satisfied: entrypoints in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from jupyter-client>=6.0.0->pandas-profiling[notebook]) (0.3)
Requirement already satisfied: tornado>=4.1 in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from jupyter-client>=6.0.0->pandas-profiling[notebook]) (6.1)
Requirement already satisfied: nest-asyncio>=1.5 in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from jupyter-client>=6.0.0->pandas-profiling[notebook]) (1.5.1)
Requirement already satisfied: pyzmq>=13 in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from jupyter-client>=6.0.0->pandas-profiling[notebook]) (22.3.0)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from jupyter-client>=6.0.0->pandas-profiling[notebook]) (2.8.2)
Requirement already satisfied: pywin32>=1.0 in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from jupyter-core>=4.6.3->pandas-profiling[notebook]) (302)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from matplotlib>=3.2.0->pandas-profiling[notebook]) (2.4.7)
Requirement already satisfied: cycler>=0.10 in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from matplotlib>=3.2.0->pandas-profiling[notebook]) (0.11.0)
Requirement already satisfied: packaging>=20.0 in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from matplotlib>=3.2.0->pandas-profiling[notebook]) (21.2)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from matplotlib>=3.2.0->pandas-profiling[notebook]) (1.3.2)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from matplotlib>=3.2.0->pandas-profiling[notebook]) (4.29.1)
Requirement already satisfied: pytz>=2020.1 in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,!=1.1.0,>=0.25.3->pandas-profiling[notebook]) (2021.3)
Collecting typing-extensions>=3.7.4.3
  Using cached typing_extensions-4.1.1-py3-none-any.whl (26 kB)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.24.0->pandas-profiling[notebook]) (1.26.7)
Requirement already satisfied: idna<4,>=2.5 in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.24.0->pandas-profiling[notebook]) (3.3)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.24.0->pandas-profiling[notebook]) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.24.0->pandas-profiling[notebook]) (2021.10.8)
Requirement already satisfied: colorama in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from tqdm>=4.48.2->pandas-profiling[notebook]) (0.4.4)
Requirement already satisfied: debugpy<2.0,>=1.0.0 in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from ipykernel>=4.5.1->ipywidgets>=7.5.1->pandas-profiling[notebook]) (1.5.1)
Requirement already satisfied: matplotlib-inline<0.2.0,>=0.1.0 in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from ipykernel>=4.5.1->ipywidgets>=7.5.1->pandas-profiling[notebook]) (0.1.3)
Requirement already satisfied: pygments in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from ipython>=4.0.0->ipywidgets>=7.5.1->pandas-profiling[notebook]) (2.10.0)
Requirement already satisfied: pickleshare in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from ipython>=4.0.0->ipywidgets>=7.5.1->pandas-profiling[notebook]) (0.7.5)
Requirement already satisfied: jedi>=0.16 in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from ipython>=4.0.0->ipywidgets>=7.5.1->pandas-profiling[notebook]) (0.18.0)
Requirement already satisfied: setuptools>=18.5 in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from ipython>=4.0.0->ipywidgets>=7.5.1->pandas-profiling[notebook]) (60.7.1)
Requirement already satisfied: decorator in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from ipython>=4.0.0->ipywidgets>=7.5.1->pandas-profiling[notebook]) (5.1.0)
Requirement already satisfied: backcall in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from ipython>=4.0.0->ipywidgets>=7.5.1->pandas-profiling[notebook]) (0.2.0)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from ipython>=4.0.0->ipywidgets>=7.5.1->pandas-profiling[notebook]) (3.0.21)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from nbformat>=4.2.0->ipywidgets>=7.5.1->pandas-profiling[notebook]) (4.1.2)
Requirement already satisfied: six>=1.5 in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil>=2.1->jupyter-client>=6.0.0->pandas-profiling[notebook]) (1.16.0)
Requirement already satisfied: notebook>=4.4.1 in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->pandas-profiling[notebook]) (6.4.5)
Requirement already satisfied: PyWavelets in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from imagehash->visions[type_image_path]==0.7.4->pandas-profiling[notebook]) (1.2.0)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from jedi>=0.16->ipython>=4.0.0->ipywidgets>=7.5.1->pandas-profiling[notebook]) (0.8.2)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.5.1->pandas-profiling[notebook]) (0.18.0)
Requirement already satisfied: nbconvert in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->pandas-profiling[notebook]) (6.2.0)
Requirement already satisfied: Send2Trash>=1.5.0 in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->pandas-profiling[notebook]) (1.8.0)
Requirement already satisfied: argon2-cffi in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->pandas-profiling[notebook]) (21.1.0)
Requirement already satisfied: terminado>=0.8.3 in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->pandas-profiling[notebook]) (0.12.1)
Requirement already satisfied: prometheus-client in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->pandas-profiling[notebook]) (0.12.0)
Requirement already satisfied: wcwidth in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=4.0.0->ipywidgets>=7.5.1->pandas-profiling[notebook]) (0.2.5)
Requirement already satisfied: pywinpty>=1.1.0 in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from terminado>=0.8.3->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->pandas-profiling[notebook]) (1.1.5)
Requirement already satisfied: cffi>=1.0.0 in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->pandas-profiling[notebook]) (1.15.0)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->pandas-profiling[notebook]) (1.5.0)
Requirement already satisfied: jupyterlab-pygments in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->pandas-profiling[notebook]) (0.1.2)
Requirement already satisfied: defusedxml in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->pandas-profiling[notebook]) (0.7.1)
Requirement already satisfied: testpath in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->pandas-profiling[notebook]) (0.5.0)
Requirement already satisfied: nbclient<0.6.0,>=0.5.0 in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->pandas-profiling[notebook]) (0.5.4)
Requirement already satisfied: mistune<2,>=0.8.1 in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->pandas-profiling[notebook]) (0.8.4)
Requirement already satisfied: bleach in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->pandas-profiling[notebook]) (4.1.0)
Requirement already satisfied: pycparser in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from cffi>=1.0.0->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->pandas-profiling[notebook]) (2.20)
Requirement already satisfied: webencodings in c:\users\mcast\appdata\local\programs\python\python310\lib\site-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->pandas-profiling[notebook]) (0.5.1)
Building wheels for collected packages: phik
  Building wheel for phik (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for phik (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [88 lines of output]
      running bdist_wheel
      running build
      running build_py
      running egg_info
      writing phik.egg-info\PKG-INFO
      writing dependency_links to phik.egg-info\dependency_links.txt
      writing entry points to phik.egg-info\entry_points.txt
      writing requirements to phik.egg-info\requires.txt
      writing top-level names to phik.egg-info\top_level.txt
      reading manifest file 'phik.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no previously-included files matching '*.py[cod]' found anywhere in distribution
      warning: no previously-included files matching '__pycache__' found anywhere in distribution
      warning: no previously-included files matching '*.so' found anywhere in distribution
      warning: no previously-included files found matching 'docs'
      warning: no previously-included files found matching 'tests'
      warning: no previously-included files found matching '.readthedocs.yml'
      warning: no previously-included files matching '*.py' found under directory 'tests'
      warning: no previously-included files matching '*' found under directory 'docs'
      adding license file 'LICENSE'
      adding license file 'NOTICE'
      running build_ext
      -- Building for: NMake Makefiles
      CMake Error at CMakeLists.txt:3 (PROJECT):
        Generator

          NMake Makefiles

        does not support platform specification, but platform

          x64

        was specified.


      CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
      -- Configuring incomplete, errors occurred!
      See also "C:/Users/mcast/AppData/Local/Temp/pip-install-81xyav9v/phik_b9c5ce38a82c4e3f98f8ef4865ba1c44/build/temp.win-amd64-3.10/Release/CMakeFiles/CMakeOutput.log".
      Traceback (most recent call last):
        File "C:\Users\mcast\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
          main()
        File "C:\Users\mcast\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\mcast\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 261, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "C:\Users\mcast\AppData\Local\Temp\pip-build-env-wye7n083\overlay\Lib\site-packages\setuptools\build_meta.py", line 244, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "C:\Users\mcast\AppData\Local\Temp\pip-build-env-wye7n083\overlay\Lib\site-packages\setuptools\build_meta.py", line 229, in _build_with_temp_dir
          self.run_setup()
        File "C:\Users\mcast\AppData\Local\Temp\pip-build-env-wye7n083\overlay\Lib\site-packages\setuptools\build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 265, in <module>
          setup(ext_modules=EXTERNAL_MODULES, **setup_args)
        File "C:\Users\mcast\AppData\Local\Temp\pip-build-env-wye7n083\overlay\Lib\site-packages\setuptools\__init__.py", line 155, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\mcast\AppData\Local\Temp\pip-build-env-wye7n083\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
          return run_commands(dist)
        File "C:\Users\mcast\AppData\Local\Temp\pip-build-env-wye7n083\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
          dist.run_commands()
        File "C:\Users\mcast\AppData\Local\Temp\pip-build-env-wye7n083\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "C:\Users\mcast\AppData\Local\Temp\pip-build-env-wye7n083\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
          cmd_obj.run()
        File "C:\Users\mcast\AppData\Local\Temp\pip-build-env-wye7n083\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "C:\Users\mcast\AppData\Local\Temp\pip-build-env-wye7n083\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\Users\mcast\AppData\Local\Temp\pip-build-env-wye7n083\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
          cmd_obj.run()
        File "C:\Users\mcast\AppData\Local\Temp\pip-build-env-wye7n083\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 135, in run
          self.run_command(cmd_name)
        File "C:\Users\mcast\AppData\Local\Temp\pip-build-env-wye7n083\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\Users\mcast\AppData\Local\Temp\pip-build-env-wye7n083\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
          cmd_obj.run()
        File "C:\Users\mcast\AppData\Local\Temp\pip-build-env-wye7n083\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 79, in run
          _build_ext.run(self)
        File "C:\Users\mcast\AppData\Local\Temp\pip-build-env-wye7n083\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 339, in run
          self.build_extensions()
        File "C:\Users\mcast\AppData\Local\Temp\pip-build-env-wye7n083\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 448, in build_extensions
          self._build_extensions_serial()
        File "C:\Users\mcast\AppData\Local\Temp\pip-build-env-wye7n083\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 473, in _build_extensions_serial
          self.build_extension(ext)
        File "setup.py", line 159, in build_extension
          subprocess.check_call(
        File "C:\Users\mcast\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\mcast\\AppData\\Local\\Temp\\pip-install-81xyav9v\\phik_b9c5ce38a82c4e3f98f8ef4865ba1c44', '-Dpybind11_DIR=C:\\Users\\mcast\\AppData\\Local\\Temp\\pip-build-env-wye7n083\\overlay\\Lib\\site-packages\\pybind11\\share\\cmake\\pybind11', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\mcast\\AppData\\Local\\Temp\\pip-install-81xyav9v\\phik_b9c5ce38a82c4e3f98f8ef4865ba1c44\\build\\lib.win-amd64-3.10\\phik\\lib', '-DPYTHON_EXECUTABLE=C:\\Users\\mcast\\AppData\\Local\\Programs\\Python\\Python310\\python.exe', '-DPHIK_VERSION_INFO=0.12.0', '-DCMAKE_BUILD_TYPE=Release', '-A', 'x64', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\mcast\\AppData\\Local\\Temp\\pip-install-81xyav9v\\phik_b9c5ce38a82c4e3f98f8ef4865ba1c44\\build\\lib.win-amd64-3.10\\phik\\lib']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for phik
Failed to build phik
ERROR: Could not build wheels for phik, which is required to install pyproject.toml-based projects`

**Comment by sbrugman** [comment]
@anajulialuizon @mcastellino Please let us know if the issue has been resolved. If not, we should forward the issue to [phik](https://github.com/KaveIO/PhiK/issues).

**Comment by Field95** [comment]
not solved by the forward suggestion. THX

> @anajulialuizon @mcastellino Please let us know if the issue has been resolved by the suggestion above, or by installing the latest version of `phik` (`pip install phik==0.12.2`). If not, we should forward the issue to [phik](https://github.com/KaveIO/PhiK/issues).

not solved by the forward suggestion. THX
